### ISSUE TITLE
Are there zero-shot text-to-image generation results?

### ISSUE THREAD

**Issue by shizhediao** [OFA-Sys/OFA#100]
Since most of the previous papers evaluate on zero-shot text-to-image generation and I noticed that you did fine-tuning.
I was wondering have you done that before or are you going to report zero-shot results?
Thanks!

**Comment by jxst539246** [comment]
Hi, we didn't evaluate zero-shot text-to-image generation on COCO, as we use an image infilling task instead of the text-to-image image generation task (which was used in previous papers) during pretraining. 
 Please check section 3.2 of our paper for the details of our pretraining task~
