### ISSUE TITLE
Are there linear probe results?

### ISSUE THREAD

**Issue by shizhediao** [OFA-Sys/OFA#101]
Hi thanks for your great work!
OFA performs very well on ImageNet fine-tuning. I am curious about its linear probe performance which is also a common practice in self-supervised learning.
Did you do that before?
Thanks!

**Comment by yangapku** [comment]
Hi, thanks for your interest for our work! Since we mainly focus on the model performance under the setting of task unification without adding any extra parameters for transferring to downstream tasks, currently we haven't tried linear probing for OFA yet.
