### ISSUE TITLE
Encoding images into base64 string for custom dataset

### ISSUE THREAD

**Issue by mudabek** [OFA-Sys/OFA#106]
Hello! Thank you for sharing your code. I am trying to run image captioning for custom dataset. As I understood I would need to change my jpg images into base64 string representation. In the paper it is said that you passed images of size 384*384.

`base64_str = base64.urlsafe_b64encode(np.random.rand(384, 384)) # bytes`
`base64_str = base64_str.decode("utf-8") `

So would I need to do something like the code above? When I run it and check the length of the string it is 1572864, but the string length of the dataset you provided is 108120. So I was wondering that maybe there is something that I am missing. Could you please clarify how to preprocess images for finetuning? What should image sizes be?

**Comment by mudabek** [comment]
Actually, I checked a few more examples from your dataset, and image sizes vary a lot. String length can even reach 50000.

**Comment by yangapku** [comment]
Hi, the base64 strings in the TSV files are obtained by performing `base64.urlsafe_b64encode()` on raw images opened by pillow (PIL) rather than resized arrays, which is the reason they vary in string lengths. The resizing from the raw size to the specified resolution is done on the fly during training and inference in the `__getitem__` method of pytorch dataset. Please use the following code to open the images and prepare the base64 strings in the TSV files:
```
from PIL import Image
from io import BytesIO
import base64

img = Image.open(file_name)
img_buffer = BytesIO()
img.save(img_buffer, format=img.format)
byte_data = img_buffer.getvalue()
base64_str = base64.b64encode(byte_data) # bytes
base64_str = base64_str.decode("utf-8") # str
```

**Comment by mudabek** [comment]
Ok thank you for clarification. Also, can I change reading to just jpg image reading (I will modify some files, I think I would need to change fairseq's iterators.py file) or is there some specific reason why I should keep it in string format?

**Comment by yangapku** [comment]
Hi, we employ base64 encoded strings to make it convenient to prepare the TSV format data files. You can just change to directly opening the image via PIL by modifying the `caption_dataset.py` file.

**Comment by mudabek** [comment]
Thank you very much!
