### ISSUE TITLE
pt file permission denied

### ISSUE THREAD

**Issue by Jihyun0510** [OFA-Sys/OFA#107]
I really appreciate your amazing work and help

I am facing permssion denied problem for model pt file when:
1) running evaluation code. thus, json file is not gererated.
2) trying to move pt file to other server

I tried to solve this problem by givig the file permission with "chmod +x file_name"
but this still does not solve the problem

do you have any idea why such "permission denied" occurs for the model weights which I gained while finetuning the captioning model?

**Comment by yangapku** [comment]
Hi, please try to use `chown` to change the owner of the directories to yourself.

**Comment by Jihyun0510** [comment]
> Hi, please try to use `chown` to change the owner of the directories to yourself.

cloning to this repo again and making new cuda environment solved the problem

Thanks for your help~!
