### ISSUE TITLE
OFA-Large vs. refcoco_large_best.pt in evaluation

### ISSUE THREAD

**Issue by hanochk** [OFA-Sys/OFA#109]
How the Pretraining model OFA-Large could be used for inference/evaluation over one of the tasks such as visual grounding?
The evaluation scripts addressing the fine-tuned model s.a. refcoco_large_best.pt and not the OFA-Large, and not supportred in the code when executing evaluate_refcoco.sh. In the code 
It can't infer the relevant task out of the ofa_large.pt model in :

    models, saved_cfg, task = checkpoint_utils.load_model_ensemble_and_task(
        utils.split_paths(cfg.common_eval.path),
        arg_overrides=overrides,
        suffix=cfg.checkpoint.checkpoint_suffix,
        strict=(cfg.checkpoint.checkpoint_shard_count == 1),
        num_shards=cfg.checkpoint.checkpoint_shard_count,

How is it possible to reproduce the ACC50% results reported in table #1 for refCOCO for instance, over the pre-trained model?
Thanks.

**Comment by logicwong** [comment]
@hanochk Hi, the results of Table 1 are based on fine-tuned models. We have updated the code to support evaluation for the pretrained models, please check out the latest code and have a try. (see `run_scripts/refcoco/evaluate_refcoco_zeroshot.sh`)
