### ISSUE TITLE
Gradio Blocks Demo

### ISSUE THREAD

**Issue by AK391** [OFA-Sys/OFA#113]
Hi, thanks for making the gradio demos here: https://huggingface.co/OFA-Sys, great work. Would you be interested in updating the demos for the gradio blocks competition this month: https://huggingface.co/Gradio-Blocks or to add another model to the competition, thanks!

**Comment by JustinLin610** [comment]
Seems very interesting! We'll take a look and try to use the new APIs and participate in the competition!
