### ISSUE TITLE
Assertion `srcIndex < srcSelectDimSize` failed.

### ISSUE THREAD

**Issue by samp830** [OFA-Sys/OFA#115]
I'm currently trying to finetune stage1 of the text to image task with a custom dataset. My dataset is large so I have sharded into multiple parts. On certain parts, I can train stage1 completely, but on some I get a RuntimeError: CUDA error: device-side assert triggered, Assertion `srcIndex < srcSelectDimSize` failed. This generally has gone away when I rerun with a smaller batch size + smaller max_src_length, but on this particular shard, it fails even with batch size=1  and max_src_length=1. Do you guys have any insights on where the error code be coming from?
Additionally, do you guys have any suggestions on what to use for num_updates / update_freq when training on different size datasets?

**Comment by jxst539246** [comment]
Hi, maybe you can check the vqgan code sequences in the failed parts. This error also happens when the token in code sequences is larger than the code vocab size (8192 in our pretrained ckpt).
