### ISSUE TITLE
How to test on VizWiz dataset

### ISSUE THREAD

**Issue by zbw-ai** [OFA-Sys/OFA#117]
Hi, thanks for your interseting work!
For VQA task, I want to use OFA on VizWiz dataset (from 2022 VizWiz Grand Challenge Workshop）. The dataset contains train, val, test, each part has a json (with iamge-ids , questions and answers) and images. How can I use OFA to test on VizWiz? Should I convert my data to tsv ( how to do it) ? Thanks for details.

**Comment by yangapku** [comment]
Hi, for other VQA-formulated datasets, please refer to issue #76, #105 (which is also related to VizWiz) and #73 for more information.
