### ISSUE TITLE
How can I change the nums of embedding layers ,encoder layer or decoder layers if I want to distill OFA model?

### ISSUE THREAD

**Issue by DavidInWuhanChina** [OFA-Sys/OFA#118]
Where is the args of Changing the nums of layers in .sh ?There is only 'arch'.

**Comment by logicwong** [comment]
You can set `--encoder-layers=x` or `--decoder-layers=x`. For more details about model args, see `models/ofa/ofa.py` and `models/ofa/unify_transformer.py`

**Comment by DavidInWuhanChina** [comment]
> You can set `--encoder-layers=x` or `--decoder-layers=x`. For more details about model args, see `models/ofa/ofa.py` and `models/ofa/unify_transformer.py`

After I change the --encoder-layers=3` or `--decoder-layers=3`. 
The problem came:
`Traceback (most recent call last):
  File "/home/liupeng/David/OFA-main/trainer.py", line 511, in load_checkpoint
    self.model.load_state_dict(
  File "/home/liupeng/anaconda3/envs/OFA/lib/python3.10/site-packages/fairseq/models/fairseq_model.py", line 125, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/home/liupeng/anaconda3/envs/OFA/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for OFAModel:
	Unexpected key(s) in state_dict: "encoder.layers.3.self_attn.c_attn", "encoder.layers.3.self_attn.k_proj.weight", "encoder.layers.3.self_attn.k_proj.bias", "encoder.layers.3.self_attn.v_proj.weight", "encoder.layers.3.self_attn.v_proj.bias", "encoder.layers.3.self_attn.q_proj.weight", "encoder.layers.3.self_attn.q_proj.bias", "encoder.layers.3.self_attn.out_proj.weight", "encoder.layers.3.self_attn.out_proj.bias", "encoder.layers.3.self_attn_layer_norm.weight", "encoder.layers.3.self_attn_layer_norm.bias", "encoder.layers.3.fc1.weight", "encoder.layers.3.fc1.bias", "encoder.layers.3.fc2.weight", "encoder.layers.3.fc2.bias", "encoder.layers.3.attn_ln.weight", "encoder.layers.3.attn_ln.bias", "encoder.layers.3.ffn_layernorm.weight", "encoder.layers.3.ffn_layernorm.bias", "encoder.layers.3.final_layer_norm.weight", "encoder.layers.3.final_layer_norm.bias", "encoder.layers.4.self_attn.c_attn", "encoder.layers.4.self_attn.k_proj.weight", "encoder.layers.4.self_attn.k_proj.bias", "encoder.layers.4.self_attn.v_proj.weight", "encoder.layers.4.self_attn.v_proj.bias", "encoder.layers.4.self_attn.q_proj.weight", "encoder.layers.4.self_attn.q_proj.bias", "encoder.layers.4.self_attn.out_proj.weight", "encoder.layers.4.self_attn.out_proj.bias", "encoder.layers.4.self_attn_layer_norm.weight", "encoder.layers.4.self_attn_layer_norm.bias", "encoder.layers.4.fc1.weight", "encoder.layers.4.fc1.bias", "encoder.layers.4.fc2.weight", "encoder.layers.4.fc2.bias", "encoder.layers.4.attn_ln.weight", "encoder.layers.4.attn_ln.bias", "encoder.layers.4.ffn_layernorm.weight", "encoder.layers.4.ffn_layernorm.bias", "encoder.layers.4.final_layer_norm.weight", "encoder.layers.4.final_layer_norm.bias", "encoder.layers.5.self_attn.c_attn", "encoder.layers.5.self_attn.k_proj.weight", "encoder.layers.5.self_attn.k_proj.bias", "encoder.layers.5.self_attn.v_proj.weight", "encoder.layers.5.self_attn.v_proj.bias", "encoder.layers.5.self_attn.q_proj.weight", "encoder.layers.5.self_attn.q_proj.bias", "encoder.layers.5.self_attn.out_proj.weight", "encoder.layers.5.self_attn.out_proj.bias", "encoder.layers.5.self_attn_layer_norm.weight", "encoder.layers.5.self_attn_layer_norm.bias", "encoder.layers.5.fc1.weight", "encoder.layers.5.fc1.bias", "encoder.layers.5.fc2.weight", "encoder.layers.5.fc2.bias", "encoder.layers.5.attn_ln.weight", "encoder.layers.5.attn_ln.bias", "encoder.layers.5.ffn_layernorm.weight", "encoder.layers.5.ffn_layernorm.bias", "encoder.layers.5.final_layer_norm.weight", "encoder.layers.5.final_layer_norm.bias", "encoder.token_rel_pos_table_list.3.weight", "encoder.token_rel_pos_table_list.4.weight", "encoder.token_rel_pos_table_list.5.weight", "encoder.image_rel_pos_table_list.3.weight", "encoder.image_rel_pos_table_list.4.weight", "encoder.image_rel_pos_table_list.5.weight", "decoder.layers.3.self_attn.c_attn", "decoder.layers.3.self_attn.k_proj.weight", "decoder.layers.3.self_attn.k_proj.bias", "decoder.layers.3.self_attn.v_proj.weight", "decoder.layers.3.self_attn.v_proj.bias", "decoder.layers.3.self_attn.q_proj.weight", "decoder.layers.3.self_attn.q_proj.bias", "decoder.layers.3.self_attn.out_proj.weight", "decoder.layers.3.self_attn.out_proj.bias", "decoder.layers.3.self_attn_ln.weight", "decoder.layers.3.self_attn_ln.bias", "decoder.layers.3.cross_attn_ln.weight", "decoder.layers.3.cross_attn_ln.bias", "decoder.layers.3.self_attn_layer_norm.weight", "decoder.layers.3.self_attn_layer_norm.bias", "decoder.layers.3.encoder_attn.c_attn", "decoder.layers.3.encoder_attn.k_proj.weight", "decoder.layers.3.encoder_attn.k_proj.bias", "decoder.layers.3.encoder_attn.v_proj.weight", "decoder.layers.3.encoder_attn.v_proj.bias", "decoder.layers.3.encoder_attn.q_proj.weight", "decoder.layers.3.encoder_attn.q_proj.bias", "decoder.layers.3.encoder_attn.out_proj.weight", "decoder.layers.3.encoder_attn.out_proj.bias", "decoder.layers.3.encoder_attn_layer_norm.weight", "decoder.layers.3.encoder_attn_layer_norm.bias", "decoder.layers.3.ffn_layernorm.weight", "decoder.layers.3.ffn_layernorm.bias", "decoder.layers.3.fc1.weight", "decoder.layers.3.fc1.bias", "decoder.layers.3.fc2.weight", "decoder.layers.3.fc2.bias", "decoder.layers.3.final_layer_norm.weight", "decoder.layers.3.final_layer_norm.bias", "decoder.layers.4.self_attn.c_attn", "decoder.layers.4.self_attn.k_proj.weight", "decoder.layers.4.self_attn.k_proj.bias", "decoder.layers.4.self_attn.v_proj.weight", "decoder.layers.4.self_attn.v_proj.bias", "decoder.layers.4.self_attn.q_proj.weight", "decoder.layers.4.self_attn.q_proj.bias", "decoder.layers.4.self_attn.out_proj.weight", "decoder.layers.4.self_attn.out_proj.bias", "decoder.layers.4.self_attn_ln.weight", "decoder.layers.4.self_attn_ln.bias", "decoder.layers.4.cross_attn_ln.weight", "decoder.layers.4.cross_attn_ln.bias", "decoder.layers.4.self_attn_layer_norm.weight", "decoder.layers.4.self_attn_layer_norm.bias", "decoder.layers.4.encoder_attn.c_attn", "decoder.layers.4.encoder_attn.k_proj.weight", "decoder.layers.4.encoder_attn.k_proj.bias", "decoder.layers.4.encoder_attn.v_proj.weight", "decoder.layers.4.encoder_attn.v_proj.bias", "decoder.layers.4.encoder_attn.q_proj.weight", "decoder.layers.4.encoder_attn.q_proj.bias", "decoder.layers.4.encoder_attn.out_proj.weight", "decoder.layers.4.encoder_attn.out_proj.bias", "decoder.layers.4.encoder_attn_layer_norm.weight", "decoder.layers.4.encoder_attn_layer_norm.bias", "decoder.layers.4.ffn_layernorm.weight", "decoder.layers.4.ffn_layernorm.bias", "decoder.layers.4.fc1.weight", "decoder.layers.4.fc1.bias", "decoder.layers.4.fc2.weight", "decoder.layers.4.fc2.bias", "decoder.layers.4.final_layer_norm.weight", "decoder.layers.4.final_layer_norm.bias", "decoder.layers.5.self_attn.c_attn", "decoder.layers.5.self_attn.k_proj.weight", "decoder.layers.5.self_attn.k_proj.bias", "decoder.layers.5.self_attn.v_proj.weight", "decoder.layers.5.self_attn.v_proj.bias", "decoder.layers.5.self_attn.q_proj.weight", "decoder.layers.5.self_attn.q_proj.bias", "decoder.layers.5.self_attn.out_proj.weight", "decoder.layers.5.self_attn.out_proj.bias", "decoder.layers.5.self_attn_ln.weight", "decoder.layers.5.self_attn_ln.bias", "decoder.layers.5.cross_attn_ln.weight", "decoder.layers.5.cross_attn_ln.bias", "decoder.layers.5.self_attn_layer_norm.weight", "decoder.layers.5.self_attn_layer_norm.bias", "decoder.layers.5.encoder_attn.c_attn", "decoder.layers.5.encoder_attn.k_proj.weight", "decoder.layers.5.encoder_attn.k_proj.bias", "decoder.layers.5.encoder_attn.v_proj.weight", "decoder.layers.5.encoder_attn.v_proj.bias", "decoder.layers.5.encoder_attn.q_proj.weight", "decoder.layers.5.encoder_attn.q_proj.bias", "decoder.layers.5.encoder_attn.out_proj.weight", "decoder.layers.5.encoder_attn.out_proj.bias", "decoder.layers.5.encoder_attn_layer_norm.weight", "decoder.layers.5.encoder_attn_layer_norm.bias", "decoder.layers.5.ffn_layernorm.weight", "decoder.layers.5.ffn_layernorm.bias", "decoder.layers.5.fc1.weight", "decoder.layers.5.fc1.bias", "decoder.layers.5.fc2.weight", "decoder.layers.5.fc2.bias", "decoder.layers.5.final_layer_norm.weight", "decoder.layers.5.final_layer_norm.bias", "decoder.token_rel_pos_table_list.3.weight", "decoder.token_rel_pos_table_list.4.weight", "decoder.token_rel_pos_table_list.5.weight", "decoder.image_rel_pos_table_list.3.weight", "decoder.image_rel_pos_table_list.4.weight", "decoder.image_rel_pos_table_list.5.weight".`

**Comment by logicwong** [comment]
@DavidInWuhanChina It seems like you loaded `ofa_base.pt`, but the architectures of this ckpt do not match your model. There are two solutions:

1. If you do not need to load the parameters of `ofa_base.pt`, please remove `--restore-file`

2. Manually delete redundant layers in `ofa_base.pt` to ensure that the architectures of the ckpt and the model can match
