### ISSUE TITLE
How do i extract VG confidence score for the beam search inference

### ISSUE THREAD

**Issue by hanochk** [OFA-Sys/OFA#119]
Hi, I was trying to observe the scores of the predicted bounding box which is in the size of beam_width. How can I get the whole bounding box prediction score (likelihood)? I can see that scores hold the beam with leading max likelihood but where all the other 4 likelihoods of the bounding box? what does finalized[0][0]['positional_scores'] stands for ?

        for sent in range(len(finalized)):
            scores = torch.tensor(
                [float(elem["score"].item()) for elem in finalized[sent]]
            )
            _, sorted_scores_indices = torch.sort(scores, descending=True)
            finalized[sent] = [finalized[sent][ssi] for ssi in sorted_scores_indices]
            finalized[sent] = torch.jit.annotate(
                List[Dict[str, Tensor]], finalized[sent]
            )
        return finalized
Thanks

**Comment by logicwong** [comment]
`finalized[0][0]['positional_scores']` contains the score of each output token. 
Normally, the output of VG contains 5 tokens: `<loc_x0> <loc_y0> <loc_x1> <loc_y1> <eos>`, so `finalized[0][0]['positional_scores'][0]` represents the score of `<loc_x0>`, `finalized[0][0]['positional_scores'][1]` represents the score of `<loc_y0>`, and so on.

**Comment by hanochk** [comment]
Thanks, then what ["score"] stands for? The ['positional_scores'] are not too indicative in terms of predicting wrong grounding. Is there a way to understand grounding with low confidence that may tell that caption is not too accurate or so?

**Comment by logicwong** [comment]
@hanochk ["score"] stands for the mean of ['positional_scores'], I think it can represent the confidence score for visual grounding.

**Comment by hanochk** [comment]
Hi unfortunately when getting wrong grounding ['score"] is still low, high
prob. Maybe refinement of caption can refine prob.?

**Comment by logicwong** [comment]
@hanochk Of course, Modifying the caption can refine the prob, you can try it.

**Comment by ZihaoZheng98** [comment]
Hi there, I ran the example code of the notebook, and I got a negative value score, is it normal?

**Comment by logicwong** [comment]
@ZihaoZheng98 It's normal, the value is log probability.
