### ISSUE TITLE
Are you planning to release OFA Huge checkpoints?

### ISSUE THREAD

**Issue by AnaRhisT94** [OFA-Sys/OFA#120]
Hi,
Are you planning to release OFA Huge checkpoints?
If yes - when?

Thanks a lot!

**Comment by JustinLin610** [comment]
Probably this or next week.

**Comment by JustinLin610** [comment]
Update: the OFA-Huge pretrained checkpoint was just released.

**Comment by AnaRhisT94** [comment]
> Update: the OFA-Huge pretrained checkpoint was just released.

What's the required GPU to run OFA-Huge?
