### ISSUE TITLE
How to use OFA for VQA inference?

### ISSUE THREAD

**Issue by Bin-ze** [OFA-Sys/OFA#122]
I want to make the functionality as in the VQA example provided by the repo.
Input image and question, output the answer to the question, how should I modify the code?

**Comment by JustinLin610** [comment]
Please refer to the instruction of VQA in the README. We have provided codes, checkpoints, and instructions for VQA and I believe there is no need to make code modification. Or if you would just like to make inference on a single example, just use our VQA demo in HF Spaces.
