### ISSUE TITLE
Question about coco captions dataset

### ISSUE THREAD

**Issue by qt2139** [OFA-Sys/OFA#128]
Hey guys, your project is really awesome. Thanks for your work.

When I was reading the paper on image captioning, I found that many authors used Karpathy's coco dataset, which contains about 120,000 images (https://arxiv.org/abs/1412.2306). Later I found out that the official coco image captions have about 330,000 pictures (https://arxiv.org/abs/1504.00325). 
What is the difference between these two datasets? Why do most authors use the first dataset? 

Thanks in advance.

**Comment by logicwong** [comment]
The processed COCO caption datasets contains 413,915 captions for 82,783 images in training, 202,520 captions for 40,504 images in validation and 379,249 captions for 40,775 images in testing. Note that the captions of the test set are not provided. 
![B65D20E4-4A0C-43B1-8197-175C695F4F79](https://user-images.githubusercontent.com/36780733/174243655-0604cd72-d9d7-4593-ba1c-007e98e2d9f4.png)


For fair and convenient comparison, Karpathy combined the training and val sets together and re-split them into training (including 123K images), val (including 5K images), test (including 5K images) sets.

**Comment by qt2139** [comment]
Yeah, I saw this part in the paper. But in the abstract, the authors say that the dataset contains over 330,000 images. This confuses me a lot. Is it because they haven't made the entire dataset yet?
![image](https://user-images.githubusercontent.com/90971979/174406884-903bb98e-7df6-4e78-8e7a-bfc46a70134c.png)

**Comment by logicwong** [comment]
@qt2139 Sorry, I'm not sure. Maybe you can ask the author?
