### ISSUE TITLE
Error in VQA and SNLI inference

### ISSUE THREAD

**Issue by sherryzyh** [OFA-Sys/OFA#129]
Hi, Thanks for your great work! I am following the readme to implement inference on VQA and SNLI.
One same error showed up in both inferences:

![image](https://user-images.githubusercontent.com/39128407/174314977-483b49e7-ef20-4138-ab29-0d7932eb119f.png)

**Comment by sherryzyh** [comment]
Solved: need to specify the "test" or "val" split when running the script.
It would be better if you could include this hint in the error message :)

**Comment by JustinLin610** [comment]
Thanks for your pointing out the issue. We'll add the notice in the readme immediately. Also it is a good advice to add it in the error message and we'll add this later.
