### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by danielgf0824** [OFA-Sys/OFA#133]
I met a strange problem during running the train_caption_stage1_base.sh(I copy the file  train_caption_stage1.sh, change restore_file and  rename it for the base model)
it just told me can not find the file
i provide the Traceback, log and my file structure
i've been puzzled for a while and even dont know where to go for a try
![image](https://user-images.githubusercontent.com/48519197/174588572-663f0d2e-19b0-4929-96c3-5ca64be7acce.png)
![image](https://user-images.githubusercontent.com/48519197/174588833-ff73cce0-82e4-48b0-950e-b4aee550db66.png)
![image](https://user-images.githubusercontent.com/48519197/174588961-9250ecb0-f2f8-4f75-b43a-0b70003977bb.png)

**Comment by logicwong** [comment]
@danielgf0824 Hi, I think this error is a shell format problem, you should remove this line `# CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --nproc_per_node=4 --master_port=${MASTER_PORT} ../../train.py \` and write the command like this:

```
for max_epoch in 5; do
  echo "max_epoch "${max_epoch}
  for warmup_ratio in 0.06; do
    echo "warmup_ratio "${warmup_ratio}
    for drop_worst_after in 6000; do
      echo "drop_worst_after "${drop_worst_after}

      log_file=${log_dir}/${max_epoch}"_"${warmup_ratio}"_"${drop_worst_after}".log"
      save_path=${save_dir}/${max_epoch}"_"${warmup_ratio}"_"${drop_worst_after}
      mkdir -p $save_path

      CUDA_VISIBLE_DEVICES=0 python3 ../../train.py \
          $data \
          --selected-cols=${selected_cols} \
          --bpe-dir=${bpe_dir} \
          --user-dir=${user_dir} \
          --restore-file=${restore_file} \
```

**Comment by danielgf0824** [comment]
@logicwong 
Thanks for your help a lot.
i'm waiting for ofa's performance!
