### ISSUE TITLE
run train_stage_caption1.sh i get the erro AssertionError: 16 < 16

### ISSUE THREAD

**Issue by chunleiml** [OFA-Sys/OFA#139]
this is the erro log
2022-06-22 15:55:56 - train.py[line:436] - INFO: begin validation on "valid" subset
slice_id 0 seek offset 0
slice_id 0 seek offset 0
Traceback (most recent call last):
  File "../../train.py", line 528, in <module>
    cli_main()
  File "../../train.py", line 521, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/mnt/hdd3/lcl/imagecaption/ofa/fairseq/fairseq/distributed/utils.py", line 389, in call_main
    main(cfg, **kwargs)
  File "../../train.py", line 190, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/mnt/hdd3/lcl/anaconda3/envs/torch1.8/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "../../train.py", line 316, in train
    cfg, trainer, task, epoch_itr, valid_subsets, end_of_epoch
  File "../../train.py", line 402, in validate_and_save
    valid_losses = validate(cfg, trainer, task, epoch_itr, valid_subsets)
  File "../../train.py", line 472, in validate
    trainer.valid_step(sample)
  File "/mnt/hdd3/lcl/anaconda3/envs/torch1.8/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/mnt/hdd3/lcl/imagecaption/ofa/trainer.py", line 1059, in valid_step
    sample, self.model, self.criterion, **extra_kwargs
  File "/mnt/hdd3/lcl/imagecaption/ofa/tasks/mm_tasks/caption.py", line 139, in valid_step
    hyps, refs = self._inference(self.sequence_generator, sample, model)
  File "/mnt/hdd3/lcl/imagecaption/ofa/tasks/mm_tasks/caption.py", line 230, in _inference
    gen_out = self.inference_step(generator, [model], sample)
  File "/mnt/hdd3/lcl/imagecaption/ofa/fairseq/fairseq/tasks/fairseq_task.py", line 518, in inference_step
    models, sample, prefix_tokens=prefix_tokens, constraints=constraints
  File "/mnt/hdd3/lcl/anaconda3/envs/torch1.8/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/hdd3/lcl/imagecaption/ofa/models/sequence_generator.py", line 207, in generate
    return self._generate(models, sample, **kwargs)
  File "/mnt/hdd3/lcl/imagecaption/ofa/models/sequence_generator.py", line 480, in _generate
    assert step < max_len, f"{step} < {max_len}"
AssertionError: 16 < 16
below is  my train_stage_caption1.sh
`#!/usr/bin/env

# The port for communication. Note that if you want to run multiple tasks on the same machine,
# you need to specify different port numbers.
export MASTER_PORT=1060
log_dir=./stage1_logs
save_dir=./stage1_checkpoints
mkdir -p $log_dir $save_dir

bpe_dir=../../utils/BPE
user_dir=../../ofa_module

data_dir=../../dataset/caption_data
data=${data_dir}/caption_stage1_train.tsv,${data_dir}/caption_val.tsv
restore_file=../../checkpoints/ofa_large.pt
selected_cols=0,4,2

task=caption
arch=ofa_large
criterion=adjust_label_smoothed_cross_entropy
label_smoothing=0.1
lr=1e-5
max_epoch=5
warmup_ratio=0.06
batch_size=1
update_freq=4
resnet_drop_path_rate=0.0
encoder_drop_path_rate=0.1
decoder_drop_path_rate=0.1
dropout=0.1
attention_dropout=0.0
max_src_length=80
max_tgt_length=20
num_bins=1000
patch_image_size=480
eval_cider_cached=${data_dir}/cider_cached_tokens/coco-valid-words.p
drop_worst_ratio=0.2

log_file="2_0.06.log"
save_path="/mnt/hdd3/lcl/imagecaption/ofa/run_scripts/caption/stage1_logs/"

CUDA_VISIBLE_DEVICES=0 python3 ../../train.py \
  $data \
  --selected-cols=${selected_cols} \
  --bpe-dir=${bpe_dir} \
  --user-dir=${user_dir} \
  --restore-file=${restore_file} \
  --reset-optimizer --reset-dataloader --reset-meters \
  --save-dir=${save_path} \
  --task=${task} \
  --arch=${arch} \
  --criterion=${criterion} \
  --label-smoothing=${label_smoothing} \
  --batch-size=${batch_size} \
  --update-freq=${update_freq} \
  --encoder-normalize-before \
  --decoder-normalize-before \
  --share-decoder-input-output-embed \
  --share-all-embeddings \
  --layernorm-embedding \
  --patch-layernorm-embedding \
  --code-layernorm-embedding \
  --resnet-drop-path-rate=${resnet_drop_path_rate} \
  --encoder-drop-path-rate=${encoder_drop_path_rate} \
  --decoder-drop-path-rate=${decoder_drop_path_rate} \
  --dropout=${dropout} \
  --attention-dropout=${attention_dropout} \
  --weight-decay=0.01 --optimizer=adam --adam-betas="(0.9,0.999)" --adam-eps=1e-08 --clip-norm=1.0 \
  --lr-scheduler=polynomial_decay --lr=${lr} \
  --max-epoch=2 --warmup-ratio=0.06 \
  --log-format=simple --log-interval=10 \
  --fixed-validation-seed=7 \
  --no-epoch-checkpoints --keep-best-checkpoints=1 \
  --save-interval=1 --validate-interval=1 \
  --save-interval-updates=500 --validate-interval-updates=500 \
  --eval-cider \
  --eval-cider-cached-tokens=${eval_cider_cached} \
  --eval-args='{"beam":5,"max_len_b":16,"no_repeat_ngram_size":3}' \
  --best-checkpoint-metric=cider --maximize-best-checkpoint-metric \
  --max-src-length=${max_src_length} \
  --max-tgt-length=${max_tgt_length} \
  --find-unused-parameters \
  --freeze-encoder-embedding \
  --freeze-decoder-embedding \
  --add-type-embedding \
  --scale-attn \
  --scale-fc \
  --scale-heads \
  --disable-entangle \
  --num-bins=${num_bins} \
  --patch-image-size=${patch_image_size} \
  --drop-worst-ratio=${drop_worst_ratio} \
  --drop-worst-after=2500 \
  --fp16 \
  --fp16-scale-window=512 \
  --num-workers=0 
`

**Comment by logicwong** [comment]
@chunleiml Hi, Can you check if the pretrained model is loaded?

**Comment by chunleiml** [comment]
> @chunleiml Hi, Can you check if the pretrained model is loaded?

I have ofa_large.pt and caption_large_best_clean.pt in ofa/checkpoints/ directory

**Comment by logicwong** [comment]
@chunleiml OK. Can you provide the full training log?

**Comment by chunleiml** [comment]
> @chunleiml OK. Can you provide the full training log?

thx, i have solve the problem by add --freeze-resnet
