### ISSUE TITLE
How could OFA demo generated caption for Pokemons image

### ISSUE THREAD

**Issue by LoomisChen** [OFA-Sys/OFA#141]
noticed that your group used open datasets as pretraining dataset and COCO as caption finetune dataset. How could OFA recognize Pokemons with no pokemon images in training dataset. THX

**Comment by logicwong** [comment]
Although COCO dataset doesn't contain Pokemon images, the pretraining dataset may contain Pokemon images. 
I think OFA still retaining what it has learned from pretraining.

**Comment by LoomisChen** [comment]
i didn't find any ACG image datasets in your paper. may i ask how much image data did you used in pretraining for the demo expect for those listed in your paper

**Comment by logicwong** [comment]
**The pretraining datasets used for the demo are consistent with that reported in our paper**. Our pertaining datasets contain  Conceptual 12M (CC12M), a large-scale dataset with 12 million image-text pairs from the Web. This dataset may contain some Pokemon images.

**Comment by LoomisChen** [comment]
meaning no offense, thx for replying
