### ISSUE TITLE
Question about use_fp16 in image captioning code

### ISSUE THREAD

**Issue by qt2139** [OFA-Sys/OFA#144]
Thanks for your work.
When I read the colab version of image captioning, I'm a little confused. 
In Preparation part, it said that: Below you just need to import required packages, and check whether to use GPU or FP16.

I have GPU, do I need set 'use_fp16' to True? Or I need set 'use_fp16' to False. Thanks in advance.
![image](https://user-images.githubusercontent.com/90971979/175796139-0d4e7e59-b405-4c05-bf71-828d29806370.png)

**Comment by logicwong** [comment]
Either True or False is ok, and the inference speed will be faster if set to True.

**Comment by qt2139** [comment]
> Either True or False is ok, and the inference speed will be slightly faster if set to True.

Thank you for your reply.
