### ISSUE TITLE
OFA-Huge Huggingface

### ISSUE THREAD

**Issue by dwlmt** [OFA-Sys/OFA#147]
Are you planning on packaging a Huggingface version of OFA-Huge soon?

**Comment by JustinLin610** [comment]
You mean Huge ckpt for HF Transformers? Yes, and btw we are going to update our code for transformers, probably next week.

**Comment by JustinLin610** [comment]
The checkpoint of OFA-huge for transformers has already been uploaded to [huggingface.co/ofa-sys](https://huggingface.co/OFA-Sys). Also, we updated the code for transformers, check the branch feature/add_transformers and transformers.md for more details.

**Comment by dwlmt** [comment]
Thank you for updating the HF code. With "git clone https://huggingface.co/OFA-Sys/OFA-huge" I get asked for authentication request (username / password) and the code is not publically visible on the HF model page like the other models and so there may be a permission issue.

**Comment by JustinLin610** [comment]
> Thank you for updating the HF code. With "git clone https://huggingface.co/OFA-Sys/OFA-huge" I get asked for authentication request (username / password) and the code is not publically visible on the HF model page like the other models and so there may be a permission issue.

I guess it is all ok with you? There should be no permission issue now.
