### ISSUE TITLE
not foundon_stage2.sh

### ISSUE THREAD

**Issue by chunleiml** [OFA-Sys/OFA#148]
when i run train_caption_stage2.sh  there are some errors

: not foundon_stage2.sh: 2: train_caption_stage2.sh:
: not foundon_stage2.sh: 6: train_caption_stage2.sh:
: not foundon_stage2.sh: 10: train_caption_stage2.sh:
: not foundon_stage2.sh: 13: train_caption_stage2.sh:
: not foundon_stage2.sh: 18: train_caption_stage2.sh:
: not foundon_stage2.sh: 39: train_caption_stage2.sh:
: not foundon_stage2.sh: 40: train_caption_stage2.sh:
: not foundon_stage2.sh: 43: train_caption_stage2.sh:
Traceback (most recent call last):
  File "../../train.py", line 528, in <module>
    cli_main()
  File "../../train.py", line 508, in cli_main
    args = options.parse_args_and_arch(parser, modify_parser=modify_parser)
  File "/mnt/hdd3/lcl/imagecaption/ofa/fairseq/fairseq/options.py", line 153, in parse_args_and_arch
    raise RuntimeError()
RuntimeError
: not foundl.tsvtrain.tsv,../../dataset/caption_data: ../../dataset/caption_data
: not foundon_stage2.sh: 46: train_caption_stage2.sh: --selected-cols=1,4,2
: not foundon_stage2.sh: 47: train_caption_stage2.sh: --bpe-dir=../../utils/BPE
: not foundon_stage2.sh: 48: train_caption_stage2.sh: --user-dir=../../ofa_module
train_caption_stage2.sh: 49: train_caption_stage2.sh: --restore-file=../../checkpoints/cap: not found_best.pt
train_caption_stage2.sh: 50: train_caption_stage2.sh: --reset-optimizer: not found
train_caption_stage2.sh: 51: train_caption_stage2.sh: --save-dir=/mnt/hdd3/lcl/imagecaptio: not foundcripts/caption/stage2_logs/
: not foundon_stage2.sh: 52: train_caption_stage2.sh: --task=caption
: not foundon_stage2.sh: 53: train_caption_stage2.sh: --arch=ofa_large
: not foundon_stage2.sh: 54: train_caption_stage2.sh: --criterion=scst_reward_criterion
: not foundon_stage2.sh: 55: train_caption_stage2.sh: --batch-size=2
: not foundon_stage2.sh: 56: train_caption_stage2.sh: --update-freq=4
train_caption_stage2.sh: 57: train_caption_stage2.sh: --encoder-normalize-before: not found
train_caption_stage2.sh: 58: train_caption_stage2.sh: --decoder-normalize-before: not found
train_caption_stage2.sh: 59: train_caption_stage2.sh: --share-decoder-input-output-embed: not found
train_caption_stage2.sh: 60: train_caption_stage2.sh: --share-all-embeddings: not found
train_caption_stage2.sh: 61: train_caption_stage2.sh: --layernorm-embedding: not found
train_caption_stage2.sh: 62: train_caption_stage2.sh: --patch-layernorm-embedding: not found
train_caption_stage2.sh: 63: train_caption_stage2.sh: --code-layernorm-embedding: not found
: not foundon_stage2.sh: 64: train_caption_stage2.sh: --resnet-drop-path-rate=0.0
: not foundon_stage2.sh: 65: train_caption_stage2.sh: --encoder-drop-path-rate=0.0
: not foundon_stage2.sh: 66: train_caption_stage2.sh: --decoder-drop-path-rate=0.0
: not foundon_stage2.sh: 67: train_caption_stage2.sh: --dropout=0.0
: not foundon_stage2.sh: 68: train_caption_stage2.sh: --attention-dropout=0.0
train_caption_stage2.sh: 69: train_caption_stage2.sh: --weight-decay=0.01: not found
train_caption_stage2.sh: 70: train_caption_stage2.sh: --lr-scheduler=polynomial_decay: not found
: not foundon_stage2.sh: 71: train_caption_stage2.sh: --max-epoch=5
train_caption_stage2.sh: 72: train_caption_stage2.sh: --log-format=simple: not found
train_caption_stage2.sh: 73: train_caption_stage2.sh: --fixed-validation-seed=7: not found
train_caption_stage2.sh: 74: train_caption_stage2.sh: --no-epoch-checkpoints: not found
train_caption_stage2.sh: 75: train_caption_stage2.sh: --save-interval=1: not found
train_caption_stage2.sh: 76: train_caption_stage2.sh: --save-interval-updates=500: not found
train_caption_stage2.sh: 77: train_caption_stage2.sh: --eval-cider: not found
train_caption_stage2.sh: 78: train_caption_stage2.sh: --eval-cider-cached-tokens=../../dat: not founded_tokens/coco-valid-words.p
train_caption_stage2.sh: 79: train_caption_stage2.sh: --eval-args={"beam":5,"max_len_b":16,"no_repeat_ngram_size":3}: not found
train_caption_stage2.sh: 80: train_caption_stage2.sh: --best-checkpoint-metric=cider: not found
: not foundon_stage2.sh: 81: train_caption_stage2.sh: --max-src-length=80
: not foundon_stage2.sh: 82: train_caption_stage2.sh: --max-tgt-length=20
train_caption_stage2.sh: 83: train_caption_stage2.sh: --find-unused-parameters: not found
train_caption_stage2.sh: 84: train_caption_stage2.sh: --freeze-encoder-embedding: not found
train_caption_stage2.sh: 85: train_caption_stage2.sh: --freeze-decoder-embedding: not found
train_caption_stage2.sh: 86: train_caption_stage2.sh: --freeze-resnet: not found
train_caption_stage2.sh: 87: train_caption_stage2.sh: --add-type-embedding: not found
train_caption_stage2.sh: 88: train_caption_stage2.sh: --scale-attn: not found
train_caption_stage2.sh: 89: train_caption_stage2.sh: --scale-fc: not found
train_caption_stage2.sh: 90: train_caption_stage2.sh: --scale-heads: not found
train_caption_stage2.sh: 91: train_caption_stage2.sh: --disable-entangle: not found
: not foundon_stage2.sh: 92: train_caption_stage2.sh: --num-bins=1000
: not foundon_stage2.sh: 93: train_caption_stage2.sh: --patch-image-size=480
train_caption_stage2.sh: 94: train_caption_stage2.sh: --scst: not found
train_caption_stage2.sh: 95: train_caption_stage2.sh: --scst-cider-cached-tokens=../../dat: not founded_tokens/coco-train-words.p
train_caption_stage2.sh: 96: train_caption_stage2.sh: --scst-args={"beam":5,"max_len_b":16,"no_repeat_ngram_size":3}: not found
train_caption_stage2.sh: 97: train_caption_stage2.sh: --memory-efficient-fp16: not found
train_caption_stage2.sh: 98: train_caption_stage2.sh: --fp16-scale-window=512: not found
train_caption_stage2.sh: 99: train_caption_stage2.sh: --num-workers=0: not found

**Comment by chunleiml** [comment]
> when i run train_caption_stage2.sh there are some errors
> 
> : not foundon_stage2.sh: 2: train_caption_stage2.sh: : not foundon_stage2.sh: 6: train_caption_stage2.sh: : not foundon_stage2.sh: 10: train_caption_stage2.sh: : not foundon_stage2.sh: 13: train_caption_stage2.sh: : not foundon_stage2.sh: 18: train_caption_stage2.sh: : not foundon_stage2.sh: 39: train_caption_stage2.sh: : not foundon_stage2.sh: 40: train_caption_stage2.sh: : not foundon_stage2.sh: 43: train_caption_stage2.sh: Traceback (most recent call last): File "../../train.py", line 528, in cli_main() File "../../train.py", line 508, in cli_main args = options.parse_args_and_arch(parser, modify_parser=modify_parser) File "/mnt/hdd3/lcl/imagecaption/ofa/fairseq/fairseq/options.py", line 153, in parse_args_and_arch raise RuntimeError() RuntimeError : not foundl.tsvtrain.tsv,../../dataset/caption_data: ../../dataset/caption_data : not foundon_stage2.sh: 46: train_caption_stage2.sh: --selected-cols=1,4,2 : not foundon_stage2.sh: 47: train_caption_stage2.sh: --bpe-dir=../../utils/BPE : not foundon_stage2.sh: 48: train_caption_stage2.sh: --user-dir=../../ofa_module train_caption_stage2.sh: 49: train_caption_stage2.sh: --restore-file=../../checkpoints/cap: not found_best.pt train_caption_stage2.sh: 50: train_caption_stage2.sh: --reset-optimizer: not found train_caption_stage2.sh: 51: train_caption_stage2.sh: --save-dir=/mnt/hdd3/lcl/imagecaptio: not foundcripts/caption/stage2_logs/ : not foundon_stage2.sh: 52: train_caption_stage2.sh: --task=caption : not foundon_stage2.sh: 53: train_caption_stage2.sh: --arch=ofa_large : not foundon_stage2.sh: 54: train_caption_stage2.sh: --criterion=scst_reward_criterion : not foundon_stage2.sh: 55: train_caption_stage2.sh: --batch-size=2 : not foundon_stage2.sh: 56: train_caption_stage2.sh: --update-freq=4 train_caption_stage2.sh: 57: train_caption_stage2.sh: --encoder-normalize-before: not found train_caption_stage2.sh: 58: train_caption_stage2.sh: --decoder-normalize-before: not found train_caption_stage2.sh: 59: train_caption_stage2.sh: --share-decoder-input-output-embed: not found train_caption_stage2.sh: 60: train_caption_stage2.sh: --share-all-embeddings: not found train_caption_stage2.sh: 61: train_caption_stage2.sh: --layernorm-embedding: not found train_caption_stage2.sh: 62: train_caption_stage2.sh: --patch-layernorm-embedding: not found train_caption_stage2.sh: 63: train_caption_stage2.sh: --code-layernorm-embedding: not found : not foundon_stage2.sh: 64: train_caption_stage2.sh: --resnet-drop-path-rate=0.0 : not foundon_stage2.sh: 65: train_caption_stage2.sh: --encoder-drop-path-rate=0.0 : not foundon_stage2.sh: 66: train_caption_stage2.sh: --decoder-drop-path-rate=0.0 : not foundon_stage2.sh: 67: train_caption_stage2.sh: --dropout=0.0 : not foundon_stage2.sh: 68: train_caption_stage2.sh: --attention-dropout=0.0 train_caption_stage2.sh: 69: train_caption_stage2.sh: --weight-decay=0.01: not found train_caption_stage2.sh: 70: train_caption_stage2.sh: --lr-scheduler=polynomial_decay: not found : not foundon_stage2.sh: 71: train_caption_stage2.sh: --max-epoch=5 train_caption_stage2.sh: 72: train_caption_stage2.sh: --log-format=simple: not found train_caption_stage2.sh: 73: train_caption_stage2.sh: --fixed-validation-seed=7: not found train_caption_stage2.sh: 74: train_caption_stage2.sh: --no-epoch-checkpoints: not found train_caption_stage2.sh: 75: train_caption_stage2.sh: --save-interval=1: not found train_caption_stage2.sh: 76: train_caption_stage2.sh: --save-interval-updates=500: not found train_caption_stage2.sh: 77: train_caption_stage2.sh: --eval-cider: not found train_caption_stage2.sh: 78: train_caption_stage2.sh: --eval-cider-cached-tokens=../../dat: not founded_tokens/coco-valid-words.p train_caption_stage2.sh: 79: train_caption_stage2.sh: --eval-args={"beam":5,"max_len_b":16,"no_repeat_ngram_size":3}: not found train_caption_stage2.sh: 80: train_caption_stage2.sh: --best-checkpoint-metric=cider: not found : not foundon_stage2.sh: 81: train_caption_stage2.sh: --max-src-length=80 : not foundon_stage2.sh: 82: train_caption_stage2.sh: --max-tgt-length=20 train_caption_stage2.sh: 83: train_caption_stage2.sh: --find-unused-parameters: not found train_caption_stage2.sh: 84: train_caption_stage2.sh: --freeze-encoder-embedding: not found train_caption_stage2.sh: 85: train_caption_stage2.sh: --freeze-decoder-embedding: not found train_caption_stage2.sh: 86: train_caption_stage2.sh: --freeze-resnet: not found train_caption_stage2.sh: 87: train_caption_stage2.sh: --add-type-embedding: not found train_caption_stage2.sh: 88: train_caption_stage2.sh: --scale-attn: not found train_caption_stage2.sh: 89: train_caption_stage2.sh: --scale-fc: not found train_caption_stage2.sh: 90: train_caption_stage2.sh: --scale-heads: not found train_caption_stage2.sh: 91: train_caption_stage2.sh: --disable-entangle: not found : not foundon_stage2.sh: 92: train_caption_stage2.sh: --num-bins=1000 : not foundon_stage2.sh: 93: train_caption_stage2.sh: --patch-image-size=480 train_caption_stage2.sh: 94: train_caption_stage2.sh: --scst: not found train_caption_stage2.sh: 95: train_caption_stage2.sh: --scst-cider-cached-tokens=../../dat: not founded_tokens/coco-train-words.p train_caption_stage2.sh: 96: train_caption_stage2.sh: --scst-args={"beam":5,"max_len_b":16,"no_repeat_ngram_size":3}: not found train_caption_stage2.sh: 97: train_caption_stage2.sh: --memory-efficient-fp16: not found train_caption_stage2.sh: 98: train_caption_stage2.sh: --fp16-scale-window=512: not found train_caption_stage2.sh: 99: train_caption_stage2.sh: --num-workers=0: not found

this is my train_option_stage2.sh
#!/usr/bin/env

# The port for communication. Note that if you want to run multiple tasks on the same machine,
# you need to specify different port numbers.
export MASTER_PORT=1060

log_dir=./stage2_logs
save_dir=./stage2_checkpoints
mkdir -p $log_dir $save_dir

bpe_dir=../../utils/BPE
user_dir=../../ofa_module

data_dir=../../dataset/caption_data
data=${data_dir}/caption_stage2_train.tsv,${data_dir}/caption_val.tsv
restore_file=../../checkpoints/caption_stage1_best.pt
selected_cols=1,4,2

task=caption
arch=ofa_large
criterion=scst_reward_criterion
label_smoothing=0.1
lr=1e-5
max_epoch=5
warmup_ratio=0.06
batch_size=2
update_freq=4
resnet_drop_path_rate=0.0
encoder_drop_path_rate=0.0
decoder_drop_path_rate=0.0
dropout=0.0
attention_dropout=0.0
max_src_length=80
max_tgt_length=20
num_bins=1000
patch_image_size=480
eval_cider_cached=${data_dir}/cider_cached_tokens/coco-valid-words.p
scst_cider_cached=${data_dir}/cider_cached_tokens/coco-train-words.p


log_file="1e-5-3.log"
save_path="/mnt/hdd3/lcl/imagecaption/ofa/run_scripts/caption/stage2_logs/"

CUDA_VISIBLE_DEVICES=1 python3 ../../train.py \
  $data \
  --selected-cols=${selected_cols} \
  --bpe-dir=${bpe_dir} \
  --user-dir=${user_dir} \
  --restore-file=${restore_file} \
  --reset-optimizer --reset-dataloader --reset-meters \
  --save-dir=${save_path} \
  --task=${task} \
  --arch=${arch} \
  --criterion=${criterion} \
  --batch-size=${batch_size} \
  --update-freq=${update_freq} \
  --encoder-normalize-before \
  --decoder-normalize-before \
  --share-decoder-input-output-embed \
  --share-all-embeddings \
  --layernorm-embedding \
  --patch-layernorm-embedding \
  --code-layernorm-embedding \
  --resnet-drop-path-rate=${resnet_drop_path_rate} \
  --encoder-drop-path-rate=${encoder_drop_path_rate} \
  --decoder-drop-path-rate=${decoder_drop_path_rate} \
  --dropout=${dropout} \
  --attention-dropout=${attention_dropout} \
  --weight-decay=0.01 --optimizer=adam --adam-betas="(0.9,0.999)" --adam-eps=1e-08 --clip-norm=1.0 \
  --lr-scheduler=polynomial_decay --lr=${lr} --end-learning-rate=2e-7 \
  --max-epoch=${max_epoch} --warmup-ratio=${warmup_ratio} \
  --log-format=simple --log-interval=10 \
  --fixed-validation-seed=7 \
  --no-epoch-checkpoints --keep-best-checkpoints=1 \
  --save-interval=1 --validate-interval=1 \
  --save-interval-updates=500 --validate-interval-updates=500 \
  --eval-cider \
  --eval-cider-cached-tokens=${eval_cider_cached} \
  --eval-args='{"beam":5,"max_len_b":16,"no_repeat_ngram_size":3}' \
  --best-checkpoint-metric=cider --maximize-best-checkpoint-metric \
  --max-src-length=${max_src_length} \
  --max-tgt-length=${max_tgt_length} \
  --find-unused-parameters \
  --freeze-encoder-embedding \
  --freeze-decoder-embedding \
  --freeze-resnet \
  --add-type-embedding \
  --scale-attn \
  --scale-fc \
  --scale-heads \
  --disable-entangle \
  --num-bins=${num_bins} \
  --patch-image-size=${patch_image_size} \
  --scst \
  --scst-cider-cached-tokens=${scst_cider_cached} \
  --scst-args='{"beam":5,"max_len_b":16,"no_repeat_ngram_size":3}' \
  --memory-efficient-fp16 \
  --fp16-scale-window=512 \
  --num-workers=0

**Comment by logicwong** [comment]
@chunleiml This issue is similar to #133 . Can you check if the format of the shell script is correct?

**Comment by logicwong** [comment]
I also recommend that your script should be consistent with our provided script.
