### ISSUE TITLE
Question about the location vocabulary

### ISSUE THREAD

**Issue by zzhanghub** [OFA-Sys/OFA#149]
OFA is an awesome job, and you maintain it meticulously! Thanks!

There is a little detail in the paper that I don't understand well. The problem is about `Location vocab`. Both text vocab and image vocab in OFA are pre-defined by word embedding or VQ-GAN. My question is, is `location vocab` pre-defined? I read the paper without finding a clear explanation. According to pixel2seq, each bin should be obtained by quantizing the input. 
However, in OFA, image, text, and location vocabs are relegated to a uniﬁed vocabulary, which means they are all pre-defined. This confuses me about how the `location vocab` works.

Could you further explain how `location vocab` works? It may include the input and output work with `location vocab`. This will be very helpful to us.

Thank you again and look forward to your reply!   : )

**Comment by logicwong** [comment]
@zzhanghub Thanks for your attention to OFA!

Yes,` location vocab` is pre-defined. We define a unified vocabulary in `ofa_task.py`. The corresponding code snippet is shown below, where `<bin_0> - <bin_999>` represent the location tokens. 

![CD8299BA-AB8C-49D4-8184-B92D4FB5B5DD](https://user-images.githubusercontent.com/36780733/176843448-dae6960d-abc8-4b55-92dd-04879869f0fe.png)

When processing the input or output coordinates, we following pix2seq to quantinize the original coordinates into discretized values, these values will be mapped to the corresponding `<bin_x>`. The code snippet is shown below:

![6E2A080B-D879-4484-BEF7-072B6C946F7B](https://user-images.githubusercontent.com/36780733/176843514-66184600-24c4-4294-bc44-e10902418f5d.png)

**Comment by dwlmt** [comment]
I have a related location question. I'm using the HF version of OFA and it's working well for captioning but I'm just trying regions and getting errors. When I try a visual grounding I get the following kinds of output.

"tensor([[    0, 58759, 58897, 58884, 58977,     2]])"

I assume that these tokens are the special bin tokens mentioned above. HF batch_decode fails with these tokens which I assume because it doesn't have them in the vocabulary. Do you have a working example of these being decoded correctly from HF?

**Comment by dwlmt** [comment]
```
 self.tokenizer.add_tokens("<mask>")
        for i in range(8192):
            self.tokenizer.add_tokens(f"<code_{i}>")
        for i in range(1000):
            self.tokenizer.add_tokens(f"<bin_{i}>")
```
Following on my above comments I tried reading the tokens to the HF tokenizer and per the above code and it now works.

**Comment by faychu** [comment]
> ```
>  self.tokenizer.add_tokens("<mask>")
>         for i in range(8192):
>             self.tokenizer.add_tokens(f"<code_{i}>")
>         for i in range(1000):
>             self.tokenizer.add_tokens(f"<bin_{i}>")
> ```
> 
> Following on my above comments I tried reading the tokens to the HF tokenizer and per the above code and it now works.

Thanks for your comments! 

Yes, in the previous version,  you could manually add these words in the way you commented. In the latest version, we have updated the ofa tokenizer, so there is no need to manually add these tokens.
