### ISSUE TITLE
Inference model using Huggingface library

### ISSUE THREAD

**Issue by fightnyy** [OFA-Sys/OFA#15]
First of all, Thanks for your amazing work.👍 
I'm very surprised at the results you've made.
But I have a question. Is it possible to use this model using the transformers library using the checkpoint of the model?
You made it possible to infer to the model in the [spaces of the transformers library](https://huggingface.co/spaces/OFA-Sys/OFA-Image_Caption), so are you planning to upload a checkpoint in the transformers library and use that library for the inference?
When I saw the colab you posted, it said how to use only fairseq
I'll be waiting for the reply.
Once again, thank you for the amazing results!

**Comment by JustinLin610** [comment]
Thanks for your appreciation! Sure we have seen a lot of users actively working on HF transformers which has strong impacts on the community, and we plan to merge our work to transformers in the near future (possibly Mar. or Apr., after we finish our release of all codes). Note that it is available to use our own codes and models to transformers when implementing demos on HF Spaces , and so it is much easier than working with transformers library.

**Comment by JustinLin610** [comment]
A recent update: we have just added support of OFA for transformers. Now it only supports inference and training requires further testing. Feel free to check it out in the "transformers" directory in the branch "feature/add_transformers", as well as checkpoints in [Models](https://huggingface.co/OFA-Sys).

**Comment by AverageName** [comment]
I'm sorry, but are you sure checkpoints work correctly in transformers? I got 
"TypeError: __init__() got multiple values for keyword argument 'decoder_start_token_id'"
When trying to run it with transformers.

!git clone --single-branch --branch feature/add_transformers https://github.com/OFA-Sys/OFA.git
!pip3 install OFA/transformers/
!git lfs install
!git clone https://huggingface.co/OFA-Sys/OFA-tiny

Used this command and used /content/OFA-tiny as ckpt_dir in example
Thanks in advance.

**Comment by AverageName** [comment]
Also this string in transformers example:
gen = model.generate(inputs, patch_img=patch_img, num_beams=4)
Should be
gen = model.generate(inputs, patch_images=patch_img, num_beams=4)

**Comment by AverageName** [comment]
Thank you, yes, now it works like a charm, I did the same changes to make it work in some way (was not quite sure that it was a right thing to do). Are you planning on releasing OFA-Large in transformers anytime soon? Really interested to use it from transformers.

Thanks once again.

**Comment by AverageName** [comment]
Looks like config.json still have an error with **decoder_start_token_id** at least for ofa-large model.

**Comment by AverageName** [comment]
Also, am I correct that this is base models from which you later fine-tuned (for ex. image captioning model), if yes, are you going to releases fine-tuned checkpoints, which are in your demos? For ex. Text2Image or Image Captioning?

**Comment by JustinLin610** [comment]
OMG! All done now. I just released the pretrained checkpoints. Releasing finetuned checkpoints might be later as we did not plan about it yet.

**Comment by AverageName** [comment]
Okay, thank you very much for you work :) Hope you'll release it soon

**Comment by fabiocomazzi** [comment]
Hi, i'm trying to test OFA base zero shot on SST2. In the following code I download SST2 data from dataset.md in OFA-Sys official repo. Basically what I'm doing, is I take the same format input used in the original paper and call the forward method of OFAForConditionalGeneration. Once I have the logits, I consider the prediction to be positivly classified if the logit corresponding to the token " positive" is greater than the one of token " negative" (and viceversa). I thought this method to be equivalent, in this simple case, to the trie based approach used in the original paper but unfortunately I get worst result (57.45% accuracy instead of 71.6%). Here is the code: 
 ```  
    model = OFAForConditionalGeneration.from_pretrained(ckpt_dir)
    tokenizer = OFATokenizer.from_pretrained(ckpt_dir)

    data = pd.read_csv(filepath_or_buffer="data/dataset/glue_dataset/sst2_data/sst2_dev.tsv", sep="\t",
                       names=["text", "label"])

    negative_id = tokenizer(" negative")["input_ids"][1]
    positive_id = tokenizer(" positive")["input_ids"][1]
    correct = 0

    model.eval()
    for i in tqdm(range(len(data))):
        with torch.no_grad():
            
            sentence = data.iloc[i]["text"]
            sentence = ' '.join(sentence.lower().strip().split()[:512])
            text = ' is the sentiment of text " {} " positive or negative?'.format(sentence)
            
            label = data.iloc[i]["label"]
            label = " positive" if label == 1 else " negative"

            inputs = tokenizer(text, max_length=1024, truncation=True, return_tensors="pt")["input_ids"]
            label_ids = tokenizer(label, max_length=1024, truncation=True, return_tensors="pt")["input_ids"][:, 1:]
            out = model(inputs, labels=label_ids)

            assert out.logits.shape[1] == 2
            pred = torch.argmax(out.logits[:, 0, [negative_id, positive_id]], dim=1).item()

            correct += 1 if pred == data.iloc[i]["label"] else 0
```
Do you think there is a flaw in my approach or this could be due to an error in the code which is still in beta?

**Comment by stevejpapad** [comment]
> A recent update: we have just added support of OFA for transformers. Now it only supports inference and training requires further testing. Feel free to check it out in the "transformers" directory in the branch "feature/add_transformers", as well as checkpoints in [Models](https://huggingface.co/OFA-Sys).

Hey Justin. I was wondering if you have compared the results from the original 'FairSeq' (FS) version with the HF one? Do they have the same weights?

I've been using the FS for zero-shot captioning on fashion imagery and i am really suprised by how well it performs. Great work btw! 

But i get significantly different results from the HF version. For example, for the same image i get "a pair of navy trousers" / "blue and green" or "a woman wearing a dress with a camouflage prin" / "camouflage" from FS / HF respectivelly. Does not seem right. Have you noticed something similar?

**Comment by AverageName** [comment]
> > A recent update: we have just added support of OFA for transformers. Now it only supports inference and training requires further testing. Feel free to check it out in the "transformers" directory in the branch "feature/add_transformers", as well as checkpoints in [Models](https://huggingface.co/OFA-Sys).
> 
> Hey Justin. I was wondering if you have compared the results from the original 'FairSeq' (FS) version with the HF one? Do they have the same weights? EDIT: I'm using OFA-Large in both cases.
> 
> I've been using the FS for zero-shot captioning on fashion imagery and i am really suprised by how well it performs. Great work btw!
> 
> But i get significantly different results from the HF version. For example, for the same image i get "a pair of navy trousers" / "blue and green" or "a woman wearing a dress with a camouflage prin" / "camouflage" from FS / HF respectivelly. Does not seem right. Have you noticed something similar?

Probably I can answer because I wanted to use this model too. The reason is that transformers library contains only base models, then for some tasks these models were fine-tuned for different task, for example, image captioning. Fairseq captioning model contains fine-tuned model and transformers one is a base one. Hope I helped you.

**Comment by JustinLin610** [comment]
> > A recent update: we have just added support of OFA for transformers. Now it only supports inference and training requires further testing. Feel free to check it out in the "transformers" directory in the branch "feature/add_transformers", as well as checkpoints in [Models](https://huggingface.co/OFA-Sys).
> 
> Hey Justin. I was wondering if you have compared the results from the original 'FairSeq' (FS) version with the HF one? Do they have the same weights? EDIT: I'm using OFA-Large in both cases.
> 
> I've been using the FS for zero-shot captioning on fashion imagery and i am really suprised by how well it performs. Great work btw!
> 
> But i get significantly different results from the HF version. For example, for the same image i get "a pair of navy trousers" / "blue and green" or "a woman wearing a dress with a camouflage prin" / "camouflage" from FS / HF respectivelly. Does not seem right. Have you noticed something similar?



> Hi, i'm trying to test OFA base zero shot on SST2. In the following code I download SST2 data from dataset.md in OFA-Sys official repo. Basically what I'm doing, is I take the same format input used in the original paper and call the forward method of OFAForConditionalGeneration. Once I have the logits, I consider the prediction to be positivly classified if the logit corresponding to the token " positive" is greater than the one of token " negative" (and viceversa). I thought this method to be equivalent, in this simple case, to the trie based approach used in the original paper but unfortunately I get worst result (57.45% accuracy instead of 71.6%). Here is the code:
> 
> ```
>    model = OFAForConditionalGeneration.from_pretrained(ckpt_dir)
>    tokenizer = OFATokenizer.from_pretrained(ckpt_dir)
> 
>    data = pd.read_csv(filepath_or_buffer="data/dataset/glue_dataset/sst2_data/sst2_dev.tsv", sep="\t",
>                       names=["text", "label"])
> 
>    negative_id = tokenizer(" negative")["input_ids"][1]
>    positive_id = tokenizer(" positive")["input_ids"][1]
>    correct = 0
> 
>    model.eval()
>    for i in tqdm(range(len(data))):
>        with torch.no_grad():
>            
>            sentence = data.iloc[i]["text"]
>            sentence = ' '.join(sentence.lower().strip().split()[:512])
>            text = ' is the sentiment of text " {} " positive or negative?'.format(sentence)
>            
>            label = data.iloc[i]["label"]
>            label = " positive" if label == 1 else " negative"
> 
>            inputs = tokenizer(text, max_length=1024, truncation=True, return_tensors="pt")["input_ids"]
>            label_ids = tokenizer(label, max_length=1024, truncation=True, return_tensors="pt")["input_ids"][:, 1:]
>            out = model(inputs, labels=label_ids)
> 
>            assert out.logits.shape[1] == 2
>            pred = torch.argmax(out.logits[:, 0, [negative_id, positive_id]], dim=1).item()
> 
>            correct += 1 if pred == data.iloc[i]["label"] else 0
> ```
> 
> Do you think there is a flaw in my approach or this could be due to an error in the code which is still in beta?

There might be some flaws in some details of the Transformer version (mainly in the generator), which might be one of the reasons. Also, zeroshot classification is very sensitive to your prompt templates. Try create more templates and see if you can achieve improvements.

**Comment by fabiocomazzi** [comment]
> > > > > A recent update: we have just added support of OFA for transformers. Now it only supports inference and training requires further testing. Feel free to check it out in the "transformers" directory in the branch "feature/add_transformers", as well as checkpoints in [Models](https://huggingface.co/OFA-Sys).
> > > > 
> > > > 
> > > > Hey Justin. I was wondering if you have compared the results from the original 'FairSeq' (FS) version with the HF one? Do they have the same weights? EDIT: I'm using OFA-Large in both cases.
> > > > I've been using the FS for zero-shot captioning on fashion imagery and i am really suprised by how well it performs. Great work btw!
> > > > But i get significantly different results from the HF version. For example, for the same image i get "a pair of navy trousers" / "blue and green" or "a woman wearing a dress with a camouflage prin" / "camouflage" from FS / HF respectivelly. Does not seem right. Have you noticed something similar?
> > > 
> > > 
> > > I just found that there might be some problems in the HF code. One is the generator (this might be a bit frustrating and cost some time), and there are also some other trivial details like the difference in attention scaling factor. I will update the code and provide a comparison test of two versions as soon as possible.
> > 
> > 
> > Thanks for the reply! Actually I tried the inference both with model.generate and with the simple forward of OFAForConditionalGenertion. While using model.generate I use max_length=min_length=3 and I constraint the model to generate only the tokens bos, " positive", " negative" and eos (this passing bad_wors_ids argument to the generate method). This yields the exact same performance as taking the most likely tokens between " positive" and "negative" coming from the logits of the forward call (i.e. model(input_ids, labels)) as I showed in the code. This is expected since these two approaches are equivalent and could maybe means that there's a prolem even for the forward method. Moreover, for what concerns the input prompt, I'm using the same as the one you used in your fairseq code (I have tried to twigle it changing some spaces but the performances are still way worst then 71). Also, for what concerns the multimodal zero-shot on SNLI-VE, following the same approach, I find worst results by just a couple of percentage points (around 47.5 instead of 49.18). In this case, the performances can be improved by increasing the resize dimension for the input image. Therfore, I tried 224, 256, 384, 512 size and the best performance I got was around 48-ish percent. In the paper I didn't found what resolution you used for OFA base zero shot on SNLI-VE, can you please share it?. Thanks again, and sorry for the long message :)
> 
> Wow let me try to answer it one by one. Well, I should admit that there are still some bugs in HF code that might not be found easily, e.g., attention scaling factor (one that matters most that we recently found), and thus your implementation on this HF codebase might not be a preferable choice. Sorry for bringing inconvenience. I did not quite get your point actually, but I understand that your conclusion is about the problematic implementation with HF. However, I think your checking should be based on the difference between the fairseq code and HF code, not just from forwarding and generating (though the diff in generators is another issue).
> 
> As to SST-2, what I mean is that our instruction for SST-2 is simply for finetuning, but not for zeroshot. Actually the variance between prompts in SST-2 are quite large, which could be over 10 points. At the moment of paper submission, around 4 months ago, we wrote rules to create a number of templates for instructions, and search for the best one to report the zeroshot result. In our next version of the paper, we will directly point out this issue about the instability caused by instructions. SNLI-VE is a bit different. The variance is much smaller, and it seems that you have achieved similar performance. We used 384 times 384 resolution for base model, so you can try with this setup. For more detailed setups, we'll later release this part of reimplementation. Later, we will gather this part of the code and release the instruction as well as the corresponding checkpoint for reimplementation. SNLI-VE first, SST-2 might be later.

Thank you for the helpfulness, I will try to optimize my prompts!

**Comment by logicwong** [comment]
> > > > > > A recent update: we have just added support of OFA for transformers. Now it only supports inference and training requires further testing. Feel free to check it out in the "transformers" directory in the branch "feature/add_transformers", as well as checkpoints in [Models](https://huggingface.co/OFA-Sys).
> > > > > 
> > > > > 
> > > > > Hey Justin. I was wondering if you have compared the results from the original 'FairSeq' (FS) version with the HF one? Do they have the same weights? EDIT: I'm using OFA-Large in both cases.
> > > > > I've been using the FS for zero-shot captioning on fashion imagery and i am really suprised by how well it performs. Great work btw!
> > > > > But i get significantly different results from the HF version. For example, for the same image i get "a pair of navy trousers" / "blue and green" or "a woman wearing a dress with a camouflage prin" / "camouflage" from FS / HF respectivelly. Does not seem right. Have you noticed something similar?
> > > > 
> > > > 
> > > > I just found that there might be some problems in the HF code. One is the generator (this might be a bit frustrating and cost some time), and there are also some other trivial details like the difference in attention scaling factor. I will update the code and provide a comparison test of two versions as soon as possible.
> > > 
> > > 
> > > Thanks for the reply! Actually I tried the inference both with model.generate and with the simple forward of OFAForConditionalGenertion. While using model.generate I use max_length=min_length=3 and I constraint the model to generate only the tokens bos, " positive", " negative" and eos (this passing bad_wors_ids argument to the generate method). This yields the exact same performance as taking the most likely tokens between " positive" and "negative" coming from the logits of the forward call (i.e. model(input_ids, labels)) as I showed in the code. This is expected since these two approaches are equivalent and could maybe means that there's a prolem even for the forward method. Moreover, for what concerns the input prompt, I'm using the same as the one you used in your fairseq code (I have tried to twigle it changing some spaces but the performances are still way worst then 71). Also, for what concerns the multimodal zero-shot on SNLI-VE, following the same approach, I find worst results by just a couple of percentage points (around 47.5 instead of 49.18). In this case, the performances can be improved by increasing the resize dimension for the input image. Therfore, I tried 224, 256, 384, 512 size and the best performance I got was around 48-ish percent. In the paper I didn't found what resolution you used for OFA base zero shot on SNLI-VE, can you please share it?. Thanks again, and sorry for the long message :)
> > 
> > 
> > Wow let me try to answer it one by one. Well, I should admit that there are still some bugs in HF code that might not be found easily, e.g., attention scaling factor (one that matters most that we recently found), and thus your implementation on this HF codebase might not be a preferable choice. Sorry for bringing inconvenience. I did not quite get your point actually, but I understand that your conclusion is about the problematic implementation with HF. However, I think your checking should be based on the difference between the fairseq code and HF code, not just from forwarding and generating (though the diff in generators is another issue).
> > As to SST-2, what I mean is that our instruction for SST-2 is simply for finetuning, but not for zeroshot. Actually the variance between prompts in SST-2 are quite large, which could be over 10 points. At the moment of paper submission, around 4 months ago, we wrote rules to create a number of templates for instructions, and search for the best one to report the zeroshot result. In our next version of the paper, we will directly point out this issue about the instability caused by instructions. SNLI-VE is a bit different. The variance is much smaller, and it seems that you have achieved similar performance. We used 384 times 384 resolution for base model, so you can try with this setup. For more detailed setups, we'll later release this part of reimplementation. Later, we will gather this part of the code and release the instruction as well as the corresponding checkpoint for reimplementation. SNLI-VE first, SST-2 might be later.
> 
> Thank you for the helpfulness, I will try to optimize my prompts!

Hi, we have uploaded the zero-shot evaluation script for SNLI-VE (slightly better than the results reported in the paper). Please check `run_scripts/snli_ve/evaluate_snli_ve_zeroshot.sh`
