### ISSUE TITLE
feature extraction for image retrieval

### ISSUE THREAD

**Issue by nikky4D** [OFA-Sys/OFA#151]
Can we use this repo to pull features out of the model for image similarity tests and text-image retrieval? Can you guide me on how to do it

**Comment by JustinLin610** [comment]
You can extract features like averaging the encoder outputs, but I am not sure about its effects as we have not done feature extraction examination before.

**Comment by nikky4D** [comment]
Thanks. I will explore the model more to see what is best for this.
