### ISSUE TITLE
update and add demos to ICML organization on Hugging Face

### ISSUE THREAD

**Issue by AK391** [OFA-Sys/OFA#154]
Hi, great work on the gradio demos for OFA on huggingface https://huggingface.co/OFA-Sys and congrats on acceptance at ICML 2022, we are having a event for ICML 2022 this month at Hugging Face, it would be great to also have the demos updated and submitted to the organization here: https://huggingface.co/ICML2022, thanks

the demos can be updated to the latest version of gradio by updating the sdk version here: https://huggingface.co/spaces/OFA-Sys/OFA-Generic_Interface/blob/main/README.md#L7 for example to 3.0.24 (latest release)

**Comment by AK391** [comment]
@logicwong the cache examples is enabled by default in spaces so that can be removed from launch() https://huggingface.co/spaces/OFA-Sys/OFA-Generic_Interface/blob/main/app.py#L216

**Comment by AK391** [comment]
@logicwong to add the demo to the ICML2022 organization you can join here https://huggingface.co/organizations/ICML2022/share/BpynfJtfsOTktlmXYoKNqqCnyufKLFXuay and clone the current space and push to this organization

**Comment by logicwong** [comment]
@AK391 Sounds interesting! We would love to participate in this event.

**Comment by AK391** [comment]
@logicwong great, we also have opened up the event to add models and datasets as well so feel free to clone and push those as well to the ICML 2022 organization for ICML papers and let me know if you need any help with this process, thanks

**Comment by logicwong** [comment]
@AK391 Thanks for your help. I want to ask you a favor, as you can see, many people want to use OFA in **transformers** library. We also submitted a [PR](https://github.com/huggingface/transformers/pull/17109) in **transformers** a month ago, but we haven't gotten a reply, can you help us speed up the progress?
