### ISSUE TITLE
How to get probabilities of answers?

### ISSUE THREAD

**Issue by 25icecreamflavors** [OFA-Sys/OFA#160]
I used models like LXMERT and Visual Bert for VQA task on COCO dataset and was able to get a list of probabilities for possible answers (there are limited number of them). How can I get probabilities here? I would like to get them with the answer: (answer, probabilities). Not just a confidence score for a one answer, but a list of probabilities distribution for all possible answers.

**Comment by logicwong** [comment]
Duplicate of #72 and #84

**Comment by JustinLin610** [comment]
check https://github.com/OFA-Sys/OFA/blob/feature/add_transformers/transformers/src/transformers/models/ofa/modeling_ofa.py , the method `get_normalized_probs` should meet your demand.
