### ISSUE TITLE
How to produce the caption for our customed images

### ISSUE THREAD

**Issue by StrixChoulala** [OFA-Sys/OFA#165]
We want to test OFA on our customed images.
Are there any instructions or how can we extract the feature of the images to put it into the OFA model?

**Comment by logicwong** [comment]
Our model accepts base64 strings as input, so you should first encode your own images into base64 strings, the code is as follows:

![B617947E-A04C-4923-970F-164FFA28997C](https://user-images.githubusercontent.com/36780733/179147186-28890a58-d74e-464b-91ad-385943da81c3.png)


Then you should prepare your own file according to README, and finally execute `evaluate.sh`. (remember to replace `data` with your own file)

![A6E103AB-4D42-4C8A-A3FE-2B2E476F2ED3](https://user-images.githubusercontent.com/36780733/179147261-334b344f-d932-494a-93cd-4f51d2e76f93.png)


In addition, you can refer to the provided colab to understand the running process of Image Captioning (https://colab.research.google.com/drive/1Q4eNhhhLcgOP4hHqwZwU1ijOlabgve1W?usp=sharing). You can also refer to some previous issues #56 #42. Hope this helps you.
