### ISSUE TITLE
Slow Downloading Speed

### ISSUE THREAD

**Issue by c-liangyu** [OFA-Sys/OFA#166]
Hi!

I am in Singapore. The download speed of models and datasets is less than 100KB/s, from aliyun servers I think. It is too slow for downloading large datasets and model checkpoints. 
May I know 
1) if this is common ?
2) any alternative way to download? 
3) upload the pre-trained and fine-tuned checkpoints to hugging face so we can use? 

Thank you!

**Comment by JustinLin610** [comment]
Good suggestion! I'll add the huggingface model links to the checkpoint.md, and give more directions in the README

**Comment by xvjiarui** [comment]
Hi @JustinLin610 

Nice work. 

I wonder if it's possible to upload fine-tuned checkpoints to Huggingface Model as it is? Or it would be an alternative download way than aliyun. I think aliyun is slow for oversea download in the default configuration.

**Comment by JustinLin610** [comment]
Sorry for missing your information (my bad...) Let me transfer the ckpts to HF models

**Comment by steve-marmalade** [comment]
Thanks for adding these, I see that you've uploaded the finetuned checkpoints for the Base size 
![image](https://user-images.githubusercontent.com/85196623/184465519-70e77b05-159f-4361-a6c9-79f0ea21eaa6.png)

Do you plan to upload the fine-tuned checkpoints [for the Large and Huge](https://github.com/OFA-Sys/OFA/blob/main/checkpoints.md#finetuning-ofa-huge) sizes as well?

Thanks for all of your work on this!

**Comment by JustinLin610** [comment]
> Thanks for adding these, I see that you've uploaded the finetuned checkpoints for the Base size ![image](https://user-images.githubusercontent.com/85196623/184465519-70e77b05-159f-4361-a6c9-79f0ea21eaa6.png)
> 
> Do you plan to upload the fine-tuned checkpoints [for the Large and Huge](https://github.com/OFA-Sys/OFA/blob/main/checkpoints.md#finetuning-ofa-huge) sizes as well?
> 
> Thanks for all of your work on this!

Sure, I'll do it soon

**Comment by skabongo2022** [comment]
Hi, 

Can you please upload as well the OFA Huge Caption ?
