### ISSUE TITLE
Data sampling of training on multiple GPUs 

### ISSUE THREAD

**Issue by La-SilverLand** [OFA-Sys/OFA#169]
hi, I'm novice to the torch distributed parallel, as far as I know, it requires distributed data sampler to partition data across multiple GPUs,  yet **I didn't find any distributed sampler in the code**.  
For single card training on my customized data, batch_size=1 works, batch_size>1 will result in OOM. 
And I've tried to run the single node 4 GPUs training, when I set the batch_size=4, the OOM error occurred, 
with batch_size=1 it is running but I wonder whether all the GPUs are processing the same data (each of them are busy checked by nvidia-smi)

How the data is distributed and how should I set the batch size ?

**Comment by logicwong** [comment]
@La-SilverLand You should set batch_size=1. In fact, the actual total batch size is equal to batch_size * update_freq * number of GPUs.

For distributed training, we manually shard the data. For example, when training on 8 data samples using 4 GPUs, we would assign sample1 and sample2 to GPU0, sample3 and sample4 to GPU1, ..., sample7 and sample8 to GPU3. The code is here: https://github.com/OFA-Sys/OFA/blob/main/data/file_dataset.py

**Comment by La-SilverLand** [comment]
thanks, my problems are solved
