### ISSUE TITLE
OFA fine tuned checkpoint for image caption task leads to some gibberish captions

### ISSUE THREAD

**Issue by KarenAssaraf** [OFA-Sys/OFA#172]
Hi!
I am running ofa inference with the ofa base pt file fine tuned on image caption task.
The results look very good except let's say 1% of the cases where I end up with captions containing gibberish words or special symbols.
I have tried to debug with the bpe decoding/beam search but without sucess.

Any idea how to go further? And understand what could be the reason for it?

Here are some examples of bad caption predicitons:

"a white house with a yard with a yard G� F F F�)"
"a fireplace in a room with a fire Al B� Wbestosbestosbestosbestos)"
"table and chairs sitting on a deck with a table and a AR A�)"

Is it due to the checkpoint quality itself? or I am missing something here?
Thanks!

**Comment by logicwong** [comment]
@KarenAssaraf When processing the data, we use transtab to remove punctuations from the captions. I suspect this might produce some incomplete gibberish captions. You can refer to the latest submitted feature/caption_fixed branch to modify your code, and we would love to hear the results.

**Comment by KarenAssaraf** [comment]
Hi @logicwong !
Thanks a lot for your answer!
But will it fix the inference? Or this fix actually require to retrain the caption finetuning without transtab function in the captions processing?

**Comment by logicwong** [comment]
@KarenAssaraf You should restart the caption finetuning using `feature/caption_fixed` branch.

**Comment by KarenAssaraf** [comment]
Makes sense, thanks!

**Comment by logicwong** [comment]
@KarenAssaraf Hi, Is your problem solved? I would love to get your feedback.
