### ISSUE TITLE
Question about NLVR2

### ISSUE THREAD

**Issue by lonestar234028** [OFA-Sys/OFA#176]
Hi experts:
Do you have any ideas about how to inference NLVR2 using OFA, since OFA can just put one image into encoder.
I was wondering can OFA accept embedding as input, so that I can concat two images encoder output together and then inference using OFA again.

All the best

**Comment by lonestar234028** [comment]
Hi exoerts:
I run this code, single image is run sucessfully, while with additional path_img_2, there is an exception:


gen = model.generate(inputs, patch_images=patch_img, patch_images_2=patch_img_2, num_beams=4)


![image](https://user-images.githubusercontent.com/11569402/180651917-bbbf0e5f-9f8f-477c-a972-cdd91f3ff46e.png)

**Comment by logicwong** [comment]
@lonestar234028 This feature (accepts two images) has not been tested. Since the pre-training tasks of OFA only accept one image, I think the best way to inference NLVR2 is to combine two images into one image. For example, during preprocessing, resize both images to the size of 256x256, and then merge them into a 512x256 image.

**Comment by lonestar234028** [comment]
Thanks @logicwong  
BTW, I have gone through the code, and I found there is an error here, however, only you can fix this, because the model need to be retained again:

https://github.com/OFA-Sys/OFA/blob/feature/add_transformers/transformers/src/transformers/models/ofa/modeling_ofa.py#L1080

will cause this error:
https://github.com/OFA-Sys/OFA/blob/feature/add_transformers/transformers/src/transformers/models/ofa/modeling_ofa.py#L851

Maybe you can change 
            self.type_embedding = Embedding(2, embed_dim, padding_idx=None)
to 
            self.type_embedding = Embedding(3, embed_dim, padding_idx=None)
