### ISSUE TITLE
Question about saving OFA as a jit script

### ISSUE THREAD

**Issue by 25icecreamflavors** [OFA-Sys/OFA#179]
Hello, I want to use OFA and need to save it. 
1. Can I somehow save it via torch jit script? I tried, but there is an error. 
2. Also, is it possible to use OFA in tensoflow and save the model there somehow?

When I save via torch script, I get the following error:
```
RuntimeError: 
'Tensor' object has no attribute or method 'bool'.:
  File "/content/OFA/models/ofa/unify_transformer.py", line 544
        h, w = image_embed.shape[-2:]
        image_num_patches = h * w
        image_padding_mask = patch_images.new_zeros((patch_images.size(0), image_num_patches)).bool()
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
```

**Comment by JustinLin610** [comment]
Never did this before, but I'll try to save it with torch jit script later. I wonder where the error comes from, would you mind telling me more details, say the version of pytorch, etc. ?

**Comment by 25icecreamflavors** [comment]
Thank you. Basically I just run your demo [colab notebook](https://colab.research.google.com/drive/1Q4eNhhhLcgOP4hHqwZwU1ijOlabgve1W?usp=sharing#scrollTo=zlDr95m6weQz) for the image captioning. The torch version is 1.12.0+cu113. I ran all cells and in the end I just do:
```
saved_model = torch.jit.script(model)
saved_model.save('saved_model.pt')
```

**Comment by JustinLin610** [comment]
Try this?
 `jit_model = torch.jit.script(model.state_dict())`

**Comment by JustinLin610** [comment]
Seemingly the problem comes from here... https://github.com/pytorch/pytorch/issues/70544

**Comment by geekinglcq** [comment]
> Thank you. Basically I just run your demo [colab notebook](https://colab.research.google.com/drive/1Q4eNhhhLcgOP4hHqwZwU1ijOlabgve1W?usp=sharing#scrollTo=zlDr95m6weQz) for the image captioning. The torch version is 1.12.0+cu113. I ran all cells and in the end I just do:
> 
> ```
> saved_model = torch.jit.script(model)
> saved_model.save('saved_model.pt')
> ```

Hi, the main problem here is `jit.script` do not support the bool operation of `Tensor` currently. 
A simple workaround is just to change the `some_tensor.new_zeros(xx, yy).bool()` to `some_tensor.new_zeros(xx, yy, dtype=torch.bool)`. You could modify the `ofa` code locally to solve it temporarily. 
Maybe we could add support for the jit script in the next version? @JustinLin610
