### ISSUE TITLE
What's the difference of data between `Pretraining` and `Vision & Language Tasks`

### ISSUE THREAD

**Issue by flymark2010** [OFA-Sys/OFA#181]
In file [dataset](https://github.com/OFA-Sys/OFA/blob/main/datasets.md), there describes the datasets for [Pretraining](https://github.com/OFA-Sys/OFA/blob/main/datasets.md#pretraining) and [Vision & Language Tasks](https://github.com/OFA-Sys/OFA/blob/main/datasets.md#vision--language-tasks). I found some are overlapped, like RefCOCO, VQAv2 etc. So what's the difference between the overlapped ones?

**Comment by logicwong** [comment]
@flymark2010 We filter our pretraining data and exclude images that appear in the validation and test sets of downstream tasks to avoid data leakage, so the downstream data (e.g., RefCOCO, VQAv2) used in pretraining is less than the original downstream data.
