### ISSUE TITLE
 How to train with image captioning and image-text matching only?

### ISSUE THREAD

**Issue by wangjk666** [OFA-Sys/OFA#183]
Hi, thanks for your awesome work. I want to pretrain OFA model on my custom datasets with image captioning and image-text matching objective, I wonder how to organize my data and whether the codebase supports this?

**Comment by logicwong** [comment]
@wangjk666 Of course, you only need to organize your own `vision_language_examples.tsv` according to the Readme, and the other three files `text_examples.tsv`, `image_examples.tsv`, `detection_examples.tsv` can be ignored.

**Comment by wangjk666** [comment]
Thanks for your reply, I tried to remove the following lines
`--text-data=${text_data} \
  --image-data=${image_data} \
  --detection-data=${detection_data} \
  --text-selected-cols=${text_selected_cols} \
  --image-selected-cols=${image_selected_cols} \
  --detection-selected-cols=${detection_selected_cols} \`

in the [scripts](https://github.com/OFA-Sys/OFA/blob/main/run_scripts/pretraining/pretrain_ofa_base.sh) that you provide, but it throws an error:

`net_output = model(**sample["net_input"])                                                                               
KeyError: 'net_input' `

**Comment by logicwong** [comment]
@wangjk666 Thanks for your feedback. We have fixed our code, please check out our latest commit and have a try.

**Comment by wangjk666** [comment]
OK, I really appreciate your help.

**Comment by wangjk666** [comment]
BTW, could you share the processed cross-modal data (which includes CC12M, CC3M, SBU, MSCOCO and VG) with me? Thanks a lot.

**Comment by wangjk666** [comment]
BTW, could you please share the processed cross-modal data (which includes CC12M, CC3M, SBU, MSCOCO and VG) with me? Thanks a lot.
