### ISSUE TITLE
training with gradient checkpointing

### ISSUE THREAD

**Issue by joellliu** [OFA-Sys/OFA#194]
Hi, I wonder if you have tried to train OFA with gradient checkpointing? I tried to do so to save GPU memory by enabling the `--checkpoint-activations` flag, but failed with the following errors:

> RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 659 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.

I tried to look it up online but could not get it work. Any suggestions? Thank you so much!

**Comment by yangapku** [comment]
Maybe you could try to add this option `--ddp-backend=legacy_ddp`, which will replace the standard torch DDP into the fairseq-implemented DDP backend.

**Comment by joellliu** [comment]
Thank you! It works!
