### ISSUE TITLE
Few shot

### ISSUE THREAD

**Issue by mattmdjaga** [OFA-Sys/OFA#203]
Is there a way to do few shots with OFA for VQA? I saw there is a zero shot function but I saw nothing about doing few shots in the code or the paper. So, was wondering if maybe i've missed something or is there a reason for not doing few shots?

**Comment by JustinLin610** [comment]
We haven't tried it. As to fewshot, fewshot by finetuning is possible, but fewshot by in-context learning as Flamingo does is still not possible due to our model and training design.
