### ISSUE TITLE
Commas in image captioning

### ISSUE THREAD

**Issue by abaybektursun** [OFA-Sys/OFA#205]
I have been training a model for couple days, however as I started inferencing I noticed there are no commas which are very important for my task.
I looked at the `caption.py` and found the line where punctuation are being set to `None`: https://github.com/OFA-Sys/OFA/blob/72cae5dfe23549d0674eeded6d73b40e3a99df10/tasks/mm_tasks/caption.py#L232
Would removing the comma from `transtab` above do the trick for me? Or should I be doing something different?

**Comment by logicwong** [comment]
@abaybektursun For your dataset, it's better to remove this trick.
