### ISSUE TITLE
Do you have plan to support much bigger dataset, such as laion

### ISSUE THREAD

**Issue by Ezra-Yu** [OFA-Sys/OFA#208]
Thank you so much for developing this awesome job!

I notice your pre-train full dataset is much smaller than the CLIP, ALIGN, and CoCa.  There are more and more open source datasets, such as [laion](https://laion.ai/blog/), which greatly improve the model, especially the vision task.

![image](https://user-images.githubusercontent.com/18586273/185565463-50585d48-c923-4656-911f-da993e58da7a.png)

Do you have plans to support such datasets to improve the model's capabilities and release the checkpoints?

**Comment by JustinLin610** [comment]
Yep we have been working on this actually, but it should take some time as it is a time-and-resource-consuming task.
