### ISSUE TITLE
chinese captions model 

### ISSUE THREAD

**Issue by zongking123** [OFA-Sys/OFA#209]
OSError: file ./utils/BERT_CN_dict/encoder.json not found

**Comment by zongking123** [comment]
1

**Comment by zongking123** [comment]
OSError: file ./utils/BERT_CN_dict/encoder.json not found

**Comment by JustinLin610** [comment]
As you closed this issue, I didn't notice it. Sorry about that. We use BERT's vocab for tokenization, so what you need is only `dict.txt` and `vocab.txt`, different from the English OFA that uses GPT's vocabulary. Did you use the shell that I uploaded for Chinese models?

**Comment by zchoi** [comment]
Yes, I have solved this problem correctly. Thanks!

**Comment by Asimok** [comment]
How to solve this problem？thanks!

**Comment by zchoi** [comment]
maybe you can try this:
<img width="635" alt="image" src="https://user-images.githubusercontent.com/30498168/194234096-6e3ef872-0fb6-4762-b142-fdf20f764de7.png">
