### ISSUE TITLE
Question regarding OpenImages dataset

### ISSUE THREAD

**Issue by RishabhMaheshwary** [OFA-Sys/OFA#215]
Hi, During pre-training OFA uses images from OpenImages dataset for tasks like detection and image infilling. Are these images only from the train split of OpenImages? I wanted to know whether their is any overlap between the validation spit of [TextVQA](https://textvqa.org/dataset/) (which also uses OpenImages) and the images used for pre-training OFA.

**Comment by logicwong** [comment]
@RishabhMaheshwary For detection, we only use the train split of OpenImages. For image infilling, we use the Complete Open Images without annotations. (https://storage.googleapis.com/openimages/web/download.html)

![0B4EF1FE-B447-4C7B-903C-AFBE337C4C16](https://user-images.githubusercontent.com/36780733/187128888-3c1fbc88-b28c-4ceb-8a94-32af4ffe155a.png)
![7CB49157-875B-4146-8940-63CC921BFA42](https://user-images.githubusercontent.com/36780733/187128905-b1490bd7-7690-49fe-b23b-6c9fa5d0abe4.png)

**Comment by RishabhMaheshwary** [comment]
Thanks for the reply!

**Comment by SpencerWhitehead** [comment]
@logicwong 
 Hello, I have a follow up question on this: In the paper you have the pre-training data table, and for the detection tasks it says that the number of samples is 3.00M. However, the train set of OpenImages alone contains 14M bounding boxes and the number of samples is different from the number of images in the table. That said, I was wondering:

1. What counts as a "sample" for detection (e.g., a single bounding box, an image + all its bounding box annotations,...)?
2. What filtering has been done to get to the 3.00M? And are the same filtering measures applied to the other detection data?

<img width="1270" alt="ofa_pretrain_data_table" src="https://user-images.githubusercontent.com/6634040/194663679-261ec002-4b35-41d7-8bb5-a8721290af5b.png">
