### ISSUE TITLE
entangle_position_embedding issue

### ISSUE THREAD

**Issue by GeorgeLuImmortal** [OFA-Sys/OFA#218]
Hello, thanks for contributing such good models. Just wondering why the default value entangle_position_embedding is False, does this mean the position embedding values are not added in the input embeddings?

**Comment by logicwong** [comment]
@GeorgeLuImmortal In this paper, we follow [TUPE](https://arxiv.org/pdf/2006.15595.pdf) to untie the position embedding. In preliminary experiments, we found that this is slightly better than adding two embeddings directly. But in recent experiments, we found that after some hyperparameter tuning (such as setting layernorm_embedding to False), adding the two embeddings directly is better than separating them.

**Comment by GeorgeLuImmortal** [comment]
> @GeorgeLuImmortal In this paper, we follow [TUPE](https://arxiv.org/pdf/2006.15595.pdf) to untie the position embedding. In preliminary experiments, we found that this is slightly better than adding two embeddings directly. But in recent experiments, we found that after some hyperparameter tuning (such as setting layernorm_embedding to False), adding the two embeddings directly is better than separating them.

Thanks for the reply, it is much clear now.
