### ISSUE TITLE
Create dataset, generate Tsv file

### ISSUE THREAD

**Issue by Carlos25130** [OFA-Sys/OFA#219]
I want to use image caption for some specific scenarios, can I generate the tsv files for my images？
like files in  `caption_data.zip` ， `caption_stage1_train.tsv, caption_stage2_train.tsv, caption_val.tsv , caption_test.tsv`
Can you share the code that generates these tsv files ？

**Comment by JustinLin610** [comment]
See [this](https://github.com/OFA-Sys/OFA#image-captioning)

**Comment by Carlos25130** [comment]
Thank you very much. I didn't read it carefully enough before.

**Comment by Carlos25130** [comment]
Does the following note mean that the object labels is not used ?
![image](https://user-images.githubusercontent.com/101075168/187812005-80a0cfbd-f3ec-4cb0-a750-ac73f71a0484.png)

**Comment by zchoi** [comment]
Yes, the predicted object labels are not used for captioning task.
