### ISSUE TITLE
CN-OFA fine-tuned model

### ISSUE THREAD

**Issue by jongjyh** [OFA-Sys/OFA#227]
Hi,

A great work indeed! If I would like to use OFA-CN for Chinese Captioning task, which model should I pick?

**Comment by JustinLin610** [comment]
It is fine to just use the pretrained model as it is pretrained on many image-text pairs. See [https://github.com/OFA-Sys/OFA/blob/main/checkpoints_cn.md](https://github.com/OFA-Sys/OFA/blob/main/checkpoints_cn.md). To achieve a better effect, finetuning on domain-specific data is recommended. Now we only provide one caption model finetuned on MUGE caption data, which are collected from the e-commerce.

**Comment by jongjyh** [comment]
Thanks! BTW how many gpus and batch size should I use for inference if I have V100 or A100 (32g/40g)?

**Comment by JustinLin610** [comment]
Inference? Base and Large models should fit the memory of your GPUS if you do not set the image resolution to an extremely large value. Then the choice of the number of GPUs and batch size all depend on your preference, e.g., the size of the data, your expected time, etc. So I guess you would like to learn more about the setups of finetuning?

**Comment by jongjyh** [comment]
yep, I want to test(without training) ofa-large-cn for my own cases, while I do not sure about experiment setting, can I just use the script `scripts/generate_caption_zh.sh`, and just follow the default setting? Also, if that work, how to arrange my data?

**Comment by JustinLin610** [comment]
Yes you can use the script and follow the default setting

**Comment by yangjianxin1** [comment]
> It is fine to just use the pretrained model as it is pretrained on many image-text pairs. See https://github.com/OFA-Sys/OFA/blob/main/checkpoints_cn.md. To achieve a better effect, finetuning on domain-specific data is recommended. Now we only provide one caption model finetuned on MUGE caption data, which are collected from the e-commerce.

How many training data do you use to finetune OFA-CN-MUGE？50000 images in the ECommerce-IC.zip from https://tianchi.aliyun.com/dataset/107332 ?
