### ISSUE TITLE
vocab.txt file in BPE

### ISSUE THREAD

**Issue by AngelicaZ** [OFA-Sys/OFA#228]
Thanks for the great work!

When I try to set the bpe cfg to 'bert', I need the `vocab.txt` file from `OFA/utils/BPE`, as it mentioned in `OFA/tasks/ofa_task.py` line 164:

![build_model](https://user-images.githubusercontent.com/34464938/188918098-d68590c5-5afa-4624-b29c-be3c8a1bd819.png)

But there is no `vocab.txt` file under the directory of `OFA/utils/BPE`, instead there is only a `dict.txt`. Are these two files work the same way?

**Comment by JustinLin610** [comment]
Thanks for pointing out the problem, and sorry about not making things clear. Actually we now only support two tokenizers, bert for Chinese and gpt2 for English (which is default). If you would like to use OFA Chinese models, you should add two lines in your script `--bpe bert` and `--bpe-dir ${bpe_dir}`, where `bpe_dir` should be `utils/BERT_CN_dict`, which looks like this:
![image](https://user-images.githubusercontent.com/27664428/188927710-d40b5271-6468-453f-889c-f329d67caea0.png)
Later I'll make it more clear in the README to avoid confusion.

**Comment by AngelicaZ** [comment]
Thanks a lot!
