### ISSUE TITLE
Pretrained checkpoint (OFA-CN-Huge)

### ISSUE THREAD

**Issue by zchoi** [OFA-Sys/OFA#230]
Thanks for the great work! When will the pretrained huge CN-checkpoint of OFA can be released？

**Comment by JustinLin610** [comment]
Sorry I haven't trained that one yet.. Now we only have the base and large models. Any problems with them now?

**Comment by zchoi** [comment]
The base and large models are great, I'm just curious about the missing of the huge model of CN version, but it doesn't hurt. Thanks for the excellent work 😁！
