### ISSUE TITLE
OFA-base pretrained model template contains some unidentified arguments for SequenceGenerator function.

### ISSUE THREAD

**Issue by AhnJunYeong0319** [OFA-Sys/OFA#235]
Good morning! At first, thanks for providing us with your splendid works and explanation on OFA.

Now I'm trying to use the code template at this [website](https://huggingface.co/OFA-Sys/OFA-base),  however, only to face few errors due to the attempt to import unknown package (```from 'generate' import sequence_generator``` - i think it should be from ```'fairseq'```). 

I'm done with several subtle problems but the main problem still remaining is that the definition of ```generator```, in the middle of the code, takes unidentified argument ```tokenizer```.

![image](https://user-images.githubusercontent.com/63603383/189775501-ccc3351f-4713-4968-a616-2fc1aece7276.png)

I also looked deeply at the source code but only to have figured out that the argument might be wrong because SeqeunceGenerator class has no parameter called ```tokenizer```. Also, the written function call omits two necessary arguments; ```models``` and ```tgt_dict```. 

Would you let me know whether the OFA-base pretrained model template works well in your local and I'm only taking something wrong or there do exist few code errors?

**Comment by JustinLin610** [comment]
> Good morning! At first, thanks for providing us with your splendid works and explanation on OFA.
> 
> Now I'm trying to use the code template at this [website](https://huggingface.co/OFA-Sys/OFA-base), however, only to face few errors due to the attempt to import unknown package (`from 'generate' import sequence_generator` - i think it should be from `'fairseq'`).
> 
> I'm done with several subtle problems but the main problem still remaining is that the definition of `generator`, in the middle of the code, takes unidentified argument `tokenizer`.
> 
> ![image](https://user-images.githubusercontent.com/63603383/189775501-ccc3351f-4713-4968-a616-2fc1aece7276.png)
> 
> I also looked deeply at the source code but only to have figured out that the argument might be wrong because SeqeunceGenerator class has no parameter called `tokenizer`. Also, the written function call omits two necessary arguments; `models` and `tgt_dict`.
> 
> Would you let me know whether the OFA-base pretrained model template works well in your local and I'm only taking something wrong or there do exist few code errors?

We have updated the part of Transformers code, and you can try this [notebook](https://colab.research.google.com/drive/1Ho81RBV8jysZ7e0FhsSCk_v938QeDuy3?usp=sharing). To learn more about the problem, see this issue https://github.com/OFA-Sys/OFA/issues/199
