### ISSUE TITLE
OFA-huge hugging face - missing merges.txt and vocab.json

### ISSUE THREAD

**Issue by willxxy** [OFA-Sys/OFA#238]
Hi I was trying to use the hugging face transformers library to finetune OFA-huge however when I pulled the model down from the hugging face repo, the merges.txt and vocab.json files were missing. What is the timeline of these releasing?

**Comment by JustinLin610** [comment]
OMG! Updated now!

**Comment by willxxy** [comment]
Thanks!

**Comment by Anirudh257** [comment]
Hi @JustinLin610 there is still an issue with the huggingface library. I get the same error: 

``HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/OFA-huge/resolve/main/vocab.json``

It works fine on modelscope though.
