### ISSUE TITLE
Multiple import errors in Open  VQA Google Colab file

### ISSUE THREAD

**Issue by petergsj** [OFA-Sys/OFA#241]
Whenever i run the open vqa colab file i encounter module not found errors as below:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-5-2ca5499a6c1e>](https://localhost:8080/#) in <module>
      2 import numpy as np
      3 import re
----> 4 from fairseq import utils,tasks
      5 from fairseq import checkpoint_utils
      6 from fairseq import distributed_utils, options, tasks, utils

15 frames
[/usr/local/lib/python3.7/dist-packages/fairseq/models/speech_to_text/convtransformer.py](https://localhost:8080/#) in <module>
     21     register_model_architecture,
     22 )
---> 23 from fairseq.models.speech_to_text.modules.convolution import infer_conv_output_dim
     24 from fairseq.models.transformer import Embedding, TransformerDecoder
     25 from fairseq.modules import LayerNorm, PositionalEmbedding, TransformerEncoderLayer

ModuleNotFoundError: No module named 'fairseq.models.speech_to_text.modules'

and similarly for from utils.zero_shot_utils import zero_shot_step

I would appreciate the help! thank you 😊

**Comment by skulshreshtha** [comment]
The problem seems more widespread. Imports dependent upon `fairseq` are failing (which I believe is because they refactored their codebase). For e.g. try running the imports in this example OFA notebook (https://colab.research.google.com/drive/1AHQNRdaUpRTgr3XySHSlba8aXwBAjwPB?usp=sharing#scrollTo=Pul6PuKKij2f). Moreover, the `fairseq` codebase that is bundled within this repository also reflects the latest state from official `fairseq` repository.

**Comment by sramshetty** [comment]
Yeah, I got around it in my notebook using (may not be the best way):
```
# clone Fairseq for installation
%cd /content
%rm -rf fairseq
!git clone --single-branch --branch 0.12.2-release https://github.com/pytorch/fairseq.git
%cd /content/fairseq
!pip install --use-feature=in-tree-build ./
```

**Comment by yangapku** [comment]
@skulshreshtha @petergsj Hi, thank you very much for pointing out this issue! We have updated the Colab notebook of open-domain VQA, which has been tested to run successfully. Please refer to [colab.md](https://github.com/OFA-Sys/OFA/blob/main/colab.md) for the link of the latest open-domain VQA notebook. We will update the Colab notebooks for other tasks as soon as possible.

**Comment by skulshreshtha** [comment]
@yangapku I have realised that if you just do `pip install fairseq` instead of using their git repository to install the package, it does not throw any errors.

**Comment by yangapku** [comment]
@skulshreshtha Hi, actually we have tried this on Colab at first, but got an error during the installation and then we turned to use the official Fairseq instead (only for inference on Colab). Anyway, now all the Colab notebooks we provide have been fixed and work well. Have a try :)
