### ISSUE TITLE
RE the training script for Transformers version of OFA 

### ISSUE THREAD

**Issue by GeorgeLuImmortal** [OFA-Sys/OFA#245]
Hi, thanks for presenting such solid work. Just wondering have you released the training script for Transformers OFA? thanks.

**Comment by JustinLin610** [comment]
@faychu just released the code for training in https://github.com/OFA-Sys/OFA-Compress. Try and see if it can help you!

**Comment by faychu** [comment]
Please try it again. I just make it public :)

**Comment by GeorgeLuImmortal** [comment]
Cool, thanks for the sharing.
