### ISSUE TITLE
AssertError in prompt tuning

### ISSUE THREAD

**Issue by Richar-Du** [OFA-Sys/OFA#246]
https://github.com/OFA-Sys/OFA/blob/3982ed1eec4230e99bcb70f34c0fead05f6643d3/models/ofa/unify_multihead_attention.py#L318

When I execute prompt tuning on the image caption task, the AssertError arises. The length of prompt is 100, so `key_padding_mask.size(1)=117`, and `k.size(1)=17`.  I'm not sure how to fix it, just skip it when performing prompt tuning?

**Comment by JustinLin610** [comment]
Bug fixed. Have another try?

**Comment by Richar-Du** [comment]
> Bug fixed. Have another try?

Thanks for your reply. But when I git pull from the branch "feature/prompt_tuning" in the repo, it says already up to date. Would you mind explaining where the update is? Thanks :)

By the way, I find that even though the `encoder_padding_mask` is not `None` in the line of https://github.com/OFA-Sys/OFA/blob/46f100614a6bbc63719f6c948594b9885a624a29/models/ofa/unify_transformer.py#L935, `encoder_padding_mask = None` in the line of https://github.com/OFA-Sys/OFA/blob/46f100614a6bbc63719f6c948594b9885a624a29/models/ofa/unify_transformer_layer.py#L263. I cannot figure out what is happening.

**Comment by JustinLin610** [comment]
Oh, prompt tuning has now been merged to the main branch. I should delete the feature branch now.

**Comment by Richar-Du** [comment]
> Oh, prompt tuning has now been merged to the main branch. I should delete the feature branch now.

Well, when I git clone from the main branch and run it, there is still the AssertError. 

By the way, I want to reproduce the result of *Prompt Tuning for Generative Multimodal Pretrained Models*, not the prompt instruction of OFA.

**Comment by JustinLin610** [comment]
My bad. Merge done now. Check the latest PR and you'll the change in the position of the assertion. You mean the detailed instruction of downstream tasks? Have you check this doc before? https://github.com/OFA-Sys/OFA/blob/main/prompt_tuning.md

**Comment by Richar-Du** [comment]
> My bad. Merge done now. Check the latest PR and you'll the change in the position of the assertion. You mean the detailed instruction of downstream tasks? Have you check this doc before? https://github.com/OFA-Sys/OFA/blob/main/prompt_tuning.md

Great! Thanks for your help! I can make it now :)
