### ISSUE TITLE
OFA-Base model checkpoints

### ISSUE THREAD

**Issue by noamwies** [OFA-Sys/OFA#25]
Could you please release the pre-trained checkpoint of OFA-Base?
Thanks

**Comment by logicwong** [comment]
We plan to release OFA-Base next week.

**Comment by noamwies** [comment]
Great, thanks!

**Comment by logicwong** [comment]
@noamwies Hi, the pre-trained checkpoint of OFA-Base has been released in this repo. To use OFA-Base, you just need to load `ofa_base.pt` (see [checkpoint.md](https://github.com/OFA-Sys/OFA/blob/main/checkpoints.md)) and change `--arch=ofa_large` to `--arch=ofa_base` in the training scripts.
