### ISSUE TITLE
Question about evaluate_vqa_beam.sh ImportError: cannot import name 'metrics' from 'fairseq' (unknown location)

### ISSUE THREAD

**Issue by litaohz** [OFA-Sys/OFA#252]
Hi experts:
I followed the step of git:
<img width="537" alt="image" src="https://user-images.githubusercontent.com/21356197/192415401-fe6371d8-d89d-4e94-8fc2-e23dff807c96.png">

And then downloaded the ckpt and dataset of VQA v2 you provided. I got this error:
Can you help me? 

<img width="709" alt="image" src="https://user-images.githubusercontent.com/21356197/192415684-f8384f9c-60d5-4ada-8e98-7508900142ba.png">

**Comment by yangapku** [comment]
Hi, please refer to issue #217 #225.
