### ISSUE TITLE
Model Initialization

### ISSUE THREAD

**Issue by shikunyu8** [OFA-Sys/OFA#255]
Thanks for sharing this great work! I have some confusions about the model initialization part: In the paper, BART weights initialization is described. However, in the ofa model code bert random initialization is used - https://github.com/OFA-Sys/OFA/blob/0b81ee973b9d0f5a546d62e240ed29e886c43613/models/ofa/ofa.py#L33

Can you help me find the BART initialization related code?

<img width="966" alt="image" src="https://user-images.githubusercontent.com/30034854/192820780-d9267601-d46b-472f-bb99-d32aede0e948.png">

**Comment by logicwong** [comment]
@shikunyu8 Since the model architecture of BART is different from OFA, we only load part of the parameters of BART, and the rest of the parameters are initialized randomly. In practice, we manually remove some layers of BART's ckpt, and then specify the `restore-file` as the processed ckpt.

**Comment by shikunyu8** [comment]
Thanks! I'm closing this issue.
