### ISSUE TITLE
generate_caption_cn.sh  has error

### ISSUE THREAD

**Issue by wuyw** [OFA-Sys/OFA#256]
omegaconf.errors.ValidationError: Cannot convert 'DictConfig' to string : '{'_name': 'bert', 'bpe_cased': False, 'bpe_vocab_file': None}'
        full_key: bpe
        reference_type=Optional[CaptionConfig]
        object_type=CaptionConfig
Fatal error condition occurred in /opt/vcpkg/buildtrees/aws-c-io/src/9e6648842a-364b708815.clean/source/event_loop.c:72: aws_thread_launch(&cleanup_thread, s_event_loop_destroy_async_thread_fn, el_group, &thread_options) == AWS_OP_SUCCESS

**Comment by JustinLin610** [comment]
The bpe override seems problematic. I just removed it and found it worked now. Try again with the updated script.

**Comment by wuyw** [comment]
> great，remove bps， it has worked
