### ISSUE TITLE
The performance on NLVR2

### ISSUE THREAD

**Issue by zd11024** [OFA-Sys/OFA#257]
Hi, have you ever finetune OFA on NLVR2? I tried to finetune by early-fusion (encoder inputs), mid-fusion (encoder outputs), and late-fusion (decoder outputs), but all the results are not very good (around 74% Acc). How do you think about? Are there better methods to finetune on NLVR2?

**Comment by logicwong** [comment]
@zd11024 We haven't tried finetuning OFA on NLVR2. Since OFA has only processed single image in the pre-training stage, I think a better way might be 1. concat the two images into one image as the input of OFA; 2. fine-tune it like SNLI-VE.

**Comment by zd11024** [comment]
I will try it later. Many thanks!
