### ISSUE TITLE
Negative examples in pre-training

### ISSUE THREAD

**Issue by RishabhMaheshwary** [OFA-Sys/OFA#259]
Hi, How are the negative examples in ```all_captions.txt``` constructed for pre-training OFA? Also, do you plan to release pre-processing scripts for the pre-training dataset. Thanks!

**Comment by logicwong** [comment]
@RishabhMaheshwary `all_captions.txt` are collected by distinct all the captions in our pretraining datasets. 
Currently we have no plans to release preprocessing scripts. Most preprocessing is done on our private platform, and it is not easy to organize these preprocessing scripts into a release-ready version.

**Comment by RishabhMaheshwary** [comment]
Thanks for the reply!
By distinct you mean, for each image taking all the n-1 captions that are not paired with that image?

**Comment by logicwong** [comment]
@RishabhMaheshwary Distinct means collecting all captions in the dataset and deduplicating them. When performing ITM task, we randomly select one caption from `all_captions.txt` as the negative caption for each image.

**Comment by RishabhMaheshwary** [comment]
Thanks for the reply!
One more question does the example pre-training all_captions.txt actually contain all the negative captions or is it just. subset?

**Comment by logicwong** [comment]
@RishabhMaheshwary It contain all the captions.

**Comment by RishabhMaheshwary** [comment]
Thanks for the reply!
