### ISSUE TITLE
Problem about finetune my own vqa dataset

### ISSUE THREAD

**Issue by amandaluof** [OFA-Sys/OFA#262]
Thanks your great work and lots of patient replies to all previous issues. Now I am finetuning my own vqa dataset. **All answers of questions in the whole dataset are "yes" or "no.".** I have tried to only change trainval_ans2label.pkl and tsv for my project. 

It can train and test successfully, but the inference speed is too slow  during inference. It needs over 70h for 8 V100 gpus, 5e6 samples. I guess there maybe some params that can be modified to match my project, especially  params about  the generated answers.  Could you please point out them?

Thanks very much :) 👍 👍

**Comment by leng-yue** [comment]
I think you can specify the [max generated sequence length](https://github.com/OFA-Sys/OFA/blob/main/models/sequence_generator.py) of the model.  
You can also try to use ONNX or torch script to accelerate inference (this requires additional work to correctly export the model).

**Comment by amandaluof** [comment]
Thanks for your advice. Following your hint, I reduce max-len-b from 200 to 60, answers are also mostly correct. However when modify it to 5, I find there are no answers for all questions in the generated result json. So [max generated sequence length](https://github.com/OFA-Sys/OFA/blob/main/models/sequence_generator.py) doesn't mean the number of generated words? What does it mean?

**Comment by leng-yue** [comment]
It means the maximum generated tokens, including special tokens like space. Moreover, one token is not equivalent to one word, some long words may be separated into multiple tokens.

**Comment by yangapku** [comment]
Hi, during the finetuning of VQA, by default we set an option `--prompt-type=prev_output` in the training script (see [train_vqa_distributed.sh](https://github.com/OFA-Sys/OFA/blob/main/run_scripts/vqa/train_vqa_distributed.sh#L141)). This option will make the model be trained to first generate the questions in the decoder-side before the answer, which functions as decoder-side condition of generation and somewhat improves the performance. During beam-search generative inference, VQA models finetuned in this way will also first be restricted to generate the question, and then goes the predicted answer. The generated question part will be discarded when dumping the result (see [eval_utils.py](https://github.com/OFA-Sys/OFA/blob/1809b55687458dbb4b1686a89b569f0efb2536e3/utils/eval_utils.py#L51)). In this scenario, the `max-len-b` accounts for both the question part and the answer part. Hence setting it to 5 will make the generation forced to end before the generation of predicted answer begins. You can either choose to set `--prompt-type=none` during finetuning to disable making the decoder first generate the question, or you should use a larger `max-len-b` to allow the question to be first generated.

**Comment by amandaluof** [comment]
> It means the maximum generated tokens, including special tokens like space. Moreover, one token is not equivalent to one word, some long words may be separated into multiple tokens.

I see. Thanks very much ! :)

**Comment by amandaluof** [comment]
> Hi, during the finetuning of VQA, by default we set an option `--prompt-type=prev_output` in the training script (see [train_vqa_distributed.sh](https://github.com/OFA-Sys/OFA/blob/main/run_scripts/vqa/train_vqa_distributed.sh#L141)). This option will make the model be trained to first generate the questions in the decoder-side before the answer, which functions as decoder-side condition of generation and somewhat improves the performance. During beam-search generative inference, VQA models finetuned in this way will also first be restricted to generate the question, and then goes the predicted answer. The generated question part will be discarded when dumping the result (see [eval_utils.py](https://github.com/OFA-Sys/OFA/blob/1809b55687458dbb4b1686a89b569f0efb2536e3/utils/eval_utils.py#L51)). In this scenario, the `max-len-b` accounts for both the question part and the answer part. Hence setting it to 5 will make the generation forced to end before the generation of predicted answer begins. You can either choose to set `--prompt-type=none` during finetuning to disable making the decoder first generate the question, or you should use a larger `max-len-b` to allow the question to be first generated.

**Comment by amandaluof** [comment]
> > Hi, during the finetuning of VQA, by default we set an option `--prompt-type=prev_output` in the training script (see [train_vqa_distributed.sh](https://github.com/OFA-Sys/OFA/blob/main/run_scripts/vqa/train_vqa_distributed.sh#L141)). This option will make the model be trained to first generate the questions in the decoder-side before the answer, which functions as decoder-side condition of generation and somewhat improves the performance. During beam-search generative inference, VQA models finetuned in this way will also first be restricted to generate the question, and then goes the predicted answer. The generated question part will be discarded when dumping the result (see [eval_utils.py](https://github.com/OFA-Sys/OFA/blob/1809b55687458dbb4b1686a89b569f0efb2536e3/utils/eval_utils.py#L51)). In this scenario, the `max-len-b` accounts for both the question part and the answer part. Hence setting it to 5 will make the generation forced to end before the generation of predicted answer begins. You can either choose to set `--prompt-type=none` during finetuning to disable making the decoder first generate the question, or you should use a larger `max-len-b` to allow the question to be first generated.

Make sense!! Thank you very much ! 👍 👍 👍
