### ISSUE TITLE
Question about RefCOCO, RefCOCO+, RefCOCOg,

### ISSUE THREAD

**Issue by RishabhMaheshwary** [OFA-Sys/OFA#266]
Hi, 
For the RefCOCO, RefCOCOg and RefCOCO+ there are different [splits](https://github.com/lichengunc/refer) from UNC, Google and Berkeley. Which split is used for OFA pre-training? Also, does the RefCOCO tsv files [here](https://github.com/OFA-Sys/OFA/blob/main/datasets.md#vision--language-tasks) is the same one that was used during pre-training? Thanks!

**Comment by logicwong** [comment]
@RishabhMaheshwary 

1. We use UNC split. 
2. Yes. The RefCOCO files provided in our repo are also used for pre-training, in addition, we removed some of these samples to avoid data leakage.

**Comment by RishabhMaheshwary** [comment]
Thanks for the reply!
