### ISSUE TITLE
using generate_cn_caption.sh

### ISSUE THREAD

**Issue by ZhaoyangLi-nju** [OFA-Sys/OFA#269]
While following the code，bash generate_cn_caption.sh

raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigKeyError: Key 'outputs' not in 'CaptionConfig'
        full_key: outputs
        reference_type=Optional[CaptionConfig]
        object_type=CaptionConfig

**Comment by JustinLin610** [comment]
I just checked and found no problem. Which checkpoint did you use?

**Comment by ZhaoyangLi-nju** [comment]
Thanks. Only occurs when using a single GPU
