### ISSUE TITLE
How to reduce the size of dataset in Image Caption

### ISSUE THREAD

**Issue by dannyxiaocn** [OFA-Sys/OFA#27]
Hi, may I ask which configuration in `train_caption_stage1.sh` should I adjust to reduce the data size in the Image Caption Task?  ( data is too big for GPU like 3090 )
I will really appreciate it if there is any help!

**Comment by logicwong** [comment]
If your GPU memory is not enough, you can reduce the batch_size and increase update_freq. Increasing update_freq may allow you to train with larger batch size when the GPU memory is small (the actual total batch size is equal to batch_size * update_freq *  number of GPUs).

**Comment by dannyxiaocn** [comment]
Great! Thank you so much!
