### ISSUE TITLE
Failed building editable for fairseq

### ISSUE THREAD

**Issue by eugfomitcheva** [OFA-Sys/OFA#270]
I am running into the following issue when running `pip install -r requirements.txt`:
```
ERROR: Failed building wheel for pycocotools
ERROR: Failed building editable for fairseq
```
 despite resetting the SETUPTOOLS_ENABLE_FEATURES variable as suggested. Is there a work-around to this or fix to bypass this compilation error?

**Comment by JustinLin610** [comment]
Did you try uninstall your old Fairseq and install ours?

**Comment by eugfomitcheva** [comment]
I am not able to install your version of fairseq using the requirements file. Would you know of any other way I can do this?

**Comment by varadgunjal** [comment]
@eugfomitcheva May I know what the solution for this was?
