### ISSUE TITLE
Attributes in Object Detection Pre-training?

### ISSUE THREAD

**Issue by SpencerWhitehead** [OFA-Sys/OFA#273]
Hello,

Thank you for the interesting work and publishing your codebase!

Looking at the provided example pre-training data, it appears that there are attributes that are used as part of the class names as well:

> 920.576,232.90200000000002,1014.784,567.954,/m/04yx4,man ( smile, stand )&&112.64,260.823,205.824,549.567,/m/04yx4,man ( stand )&&95.232,265.59000000000003,180.224,555.015,/m/01xyhv,suit&&275.456,271.719,357.376,510.75,/m/04yx4,man ( stand )&&167.936,254.694,239.616,526.413,/m/04yx4,man ( stand )&&577.536,254.694,652.288,512.112,/m/04yx4,man ( smile, stand )&&215.04,260.142,288.768,516.198,/m/04yx4,man ( smile, stand )&&507.904,267.63300000000004,588.8,488.277,/m/04yx4,man ( smile, stand )&&765.952,271.719,833.536,525.051,/m/04yx4,man ( smile, stand )&&440.32,268.995,513.024,498.49199999999996,/m/04yx4,man ( stand )&&642.048,279.89099999999996,704.512,505.302,/m/04yx4,man ( smile, stand )&&333.824,258.78000000000003,391.168,485.553,/m/04yx4,man ( stand )&&671.744,271.038,718.848,495.087,/m/04yx4,man ( smile, stand )&&72.704,237.66899999999998,145.408,335.052,/m/04yx4,man ( stand )&&618.496,260.142,663.552,335.052,/m/04yx4,man ( stand )&&418.816,275.805,464.896,335.052,/m/04yx4,man ( smile, stand )

This specific annotation appears to come from OpenImages. When preparing the pre-training data, should we include attributes in order to reproduce your pre-training results? If so, which datasets do you include attributes for and should the formatting be exactly what is shown in this example across all datasets (i.e., "( attribute1, attribute2,... )")?

Thank you very much!

**Comment by logicwong** [comment]
@SpencerWhitehead I think these properties should be preserved because they contain rich information, which is useful for vision-language pretraining.
In fact, we only include attributes for OpenImages. As for the format of attributes, we just chose the simplest way, there should be a better way to format these attributes.
