### ISSUE TITLE
Initializing from BART

### ISSUE THREAD

**Issue by SpencerWhitehead** [OFA-Sys/OFA#274]
Hello,

For initializing from the BART weights, can you say more specifically which weights are taken from BART and which ones are randomly initialized? Both in the paper and #255 , say that some weights are taken from BART while others are randomly initialized, so I wanted to clarify.

From what I can tell, based on the differences in architecture, the added components that BART doesn't have (e.g., embeddings for image codes, objects, position embeddings for visual info, extra layer norms) are randomly initialized. Is everything else initialized from BART?

Also, do you use the BART weights from here (https://github.com/facebookresearch/fairseq/blob/main/examples/bart/README.md#pre-trained-models)?

Thanks in advance!

**Comment by logicwong** [comment]
@SpencerWhitehead Thanks for your attention to OFA. We randomly initialize the following parameters:
1. embeddings for image codes, objects
2. position embeddings for visual info
3. relative position bias for visual and text
4. self.attn_ln, self.ffn_layernorm and self.c_attn (normformer related parameters)

Other parameters are initialized from BART or pretrained ResNet.

We do use the BART weights from https://github.com/facebookresearch/fairseq/blob/main/examples/bart/README.md#pre-trained-models.
The ResNet weights are from torchvision (e.g., https://download.pytorch.org/models/resnet152-394f9c45.pth)
