### ISSUE TITLE
OFA-Large Image Caption model on Huggingface?

### ISSUE THREAD

**Issue by logan-markewich** [OFA-Sys/OFA#276]
Are you able to convert OFA-Large (finetuned for image captioning) to huggingface format? It would make the download process and using the model with your huggingface branch a lot easier :)

I think this is the model? https://ofa-silicon.oss-us-west-1.aliyuncs.com/checkpoints/caption_large_best_clean.pt
But the checkpoint format will not work with huggingface for now

**Comment by JustinLin610** [comment]
Will do it soon!

**Comment by faychu** [comment]
Thanks for your attention! Please try this checkpoint (https://huggingface.co/OFA-Sys/ofa-caption-large). If you want to learn more about how to use the huggingface ckpt for finetuning or inference, you can see the repo https://github.com/OFA-Sys/OFA-Compress

**Comment by logan-markewich** [comment]
@JustinLin610 Awesome, thanks!! 💪🏻 

@faychu Thanks for the links! However, that checkpoint is not fine-tuned for image captioning, and I don't have the resources to fine-tune the model myself.
