### ISSUE TITLE
Questions about the data proportion of each task

### ISSUE THREAD

**Issue by zzhanghub** [OFA-Sys/OFA#277]
The OFA pre-training phase uses many different types of data, such as caption, VQA, and VG. In each epoch, is there any deliberate adjustment of the proportion of these data? I have the following two specific questions:

1. From the code,  I see that the sampling frequency of MLM and Image Infilling has been reduced to 1/8. This is reasonable because the tsv file of the visual language task contains multiple tasks. But I still wonder if the ratio of 1/8 has been specially adjusted by experimental verification.
2. For the VL tsv, I cannot know the proportion of each task. In my opinion, CC12M has too many data. It seems unreasonable to shuffle directly with other tasks. Do you have any experience in the proportion of data in each task?

Thank you!

**Comment by logicwong** [comment]
@zzhanghub 
1. We haven‘t experimentally tested this ratio. The ratio 1/8 was chosen based on a trade-off between effectiveness and efficiency.
2. Although the caption data is larger than others, their proportions are not very disparate, so for convenience, we directly shuffle all the VL data.

I found that you have raised a lot of questions in our repo and sometimes I can't reply to you in time, would you mind sending me an email so we can communicate via email? (or other
