### ISSUE TITLE
How to add a new task？

### ISSUE THREAD

**Issue by CCYChongyanChen** [OFA-Sys/OFA#280]
Thank you for sharing this great work! Could you kindly guide how to add a new task to this model?
The goal is to predict if a visual question looks at the same region or different regions for all unique answers to the visual question. In other words, since a visual question might have different valid answers and each answer can refer to a region. We would like to know if the answers are referring to the same region or different regions.
The input is an image and a question, the output is yes/no. This is a binary classification problem.

(1) Following  https://github.com/OFA-Sys/OFA/issues/239#issuecomment-1247624064_, what prompts do you suggest we use?
My thought is some prompt like "Does this image has multiple answers referring to the same region?"
(2) How to fine-tune this model with the new binary classification task?

Thank you so much!

**Comment by JustinLin610** [comment]
Create a new dataset and a new task by adding python files to the `data` and `task`, following the way we do. We have transformed all tasks to seq2seq, so it might be different from other codes for classification. You can check the code of SST-2, which is also a binary classification for some hints.
