### ISSUE TITLE
I would like to ask what GPU you use to run；I only have 4 P100

### ISSUE THREAD

**Issue by Rushing-Life** [OFA-Sys/OFA#282]

**Comment by JustinLin610** [comment]
We mainly use V100 or A100. P100 can also be an option for base-size models I think.

**Comment by saffie91** [comment]
Is this for inference on huggingface?

**Comment by JustinLin610** [comment]
Nothing to do with HF. Both original code or HF code of OFA should be available.

**Comment by faychu** [comment]
> No I mean is the huggingface demo using V100s for inference? I wanna know how fast this would work roughly, so knowing what you guys are using on huggingface would give a good insight on how it would work on the edge device. Any tips for edge inference would be appreciated also.

For OFA inference, finetuning or distillation on huggingface, you can refer to our OFA-compress repo (https://github.com/OFA-Sys/OFA-Compress).  You can use V100s for inference on this repo, and it is about 0.17 second per sample on image caption task with one V100 GPU.
