### ISSUE TITLE
question about cn model

### ISSUE THREAD

**Issue by dinglei8908** [OFA-Sys/OFA#283]
I wonder know what data and how large of the data are used to pretrain the cn model?
are all pretraining data open-source available?

**Comment by dinglei8908** [comment]
I wonder know what data and how large of the data are used to pretrain the cn model?
are all pretraining data open-source available?

**Comment by JustinLin610** [comment]
The datasets mostly consists of the Chinese data of LAION-5B, Wukong Dataset (subset of around 70m samples), transaltion of COCO and VG. I think it is possible to use these data to reproduce the performance.
