### ISSUE TITLE
Using OFA for visual grounding

### ISSUE THREAD

**Issue by 25icecreamflavors** [OFA-Sys/OFA#288]
Hello, I saw, that there is a demo on a huggingface, I could enter description of an object and get it's box on the image. Can I use model in code for my datasets? Is it possible to use model for this task from huggingface framework? Can I finetune OFA on my dataset for this task? I read the description of this repository, but didn't find about this task, maybe I missed it.

**Comment by JustinLin610** [comment]
![image](https://user-images.githubusercontent.com/27664428/200096953-0e29ef56-3a8a-468d-840e-e95c05da02bb.png)
Check here for the instruction:)

**Comment by 25icecreamflavors** [comment]
@JustinLin610 thank you, I missed it. But still, it is possible to use my own datasets? Should I just make them in the format like refcoco? And if I use wy dataset, which of the scripts for finetuning should I run?

**Comment by JustinLin610** [comment]
Yes. What you need to do is to format your data as refcoco, and still use the script for refcoco. This should be fine.

**Comment by 25icecreamflavors** [comment]
This is an example of data from the readme. What is the order of coordinates here? Is it x0 (left), y0 (bottom), x1 (right), y1 (top)?
`79_1    237367  A woman in a white blouse holding a glass of wine.  230.79,121.75,423.66,463.06 9j/4AAQ...1pAz/9k=`

**Comment by 25icecreamflavors** [comment]
After evaluation, it seems that correct order actually was: x0 (left), y0 (top), x1 (right), y1 (bottom).
