### ISSUE TITLE
Get raw image file for visualization examples in OFA

### ISSUE THREAD

**Issue by 2003pro** [OFA-Sys/OFA#290]
Dear OFA authors,

I am trying to test OFA and some other image-text Pretrained LMs by case analysis. Since your visualization in Figure 7-11 is quite impressive, I am wondering if I could get the raw file from you so that I can get more fair comparison. (The composition picture in https://github.com/OFA-Sys/OFA/tree/main/examples is not that clear and may affect visualization results.)

**Comment by logicwong** [comment]
@2003pro Sorry for the late reply, we put the raw image files [here](https://ofa-beijing.oss-cn-beijing.aliyuncs.com/datasets/ofa_images.zip)
