### ISSUE TITLE
Question About FID calculation

### ISSUE THREAD

**Issue by amandaluof** [OFA-Sys/OFA#295]
Thanks your great work and lots of patient replies to all previous issues. Now I am testing the performance of image generation task for OFA on COCO 2017. Since you directly give the distribution of gt images(ie. ./run_scripts/image_gen/gt_stat.npz) for COCO2014. So could you please share your calculation method ? I am not sure whether you use padding, resize or other operations when calculate gt images' distribution.

**Comment by JustinLin610** [comment]
https://github.com/OFA-Sys/OFA/blob/main/run_scripts/image_gen/fid_score.py here provides the code and we only resize the gt images
