### ISSUE TITLE
suggestions for evaluation on NLP tasks?

### ISSUE THREAD

**Issue by taokz** [OFA-Sys/OFA#302]
Hi!

I would like to evaluate glue-like datasets but I didn't find the evaluation script for them. I wrote a script on NLI task as follows, 

user_dir=../../ofa_module
bpe_dir=../../utils/BPE

data=/data/processed_data/tune/nli/nli_test.tsv
path=/data/uned_checkpoints/nli/20_7e-5_2/checkpoint_best.pt
result_path=../../results/nli
selected_cols=0,1,2
split='test'

python3 -m torch.distributed.launch --nproc_per_node=${GPUS_PER_NODE} --master_port=${MASTER_PORT} ../../evaluate.py \
    ${data} \
    --path=${path} \
    --user-dir=${user_dir} \
    --task=mnli \
    --batch-size=16 \
    --log-format=simple --log-interval=10 \
    --seed=7 \
    --gen-subset=${split} \
    --results-path=${result_path} \
    --fp16 \
    --num-workers=0 \
    --model-overrides="{\"data\":\"${data}\",\"bpe_dir\":\"${bpe_dir}\",\"selected_cols\":\"${selected_cols}\"}"

but I got the error
```
Traceback (most recent call last):
  File "../../evaluate.py", line 156, in <module>
    cli_main()
  File "../../evaluate.py", line 151, in cli_main
    cfg, main, ema_eval=args.ema_eval, beam_search_vqa_eval=args.beam_search_vqa_eval, zero_shot=args.zero_shot
  File "/home/user/ofa/fairseq/fairseq/distributed/utils.py", line 374, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/home/user/ofa/fairseq/fairseq/distributed/utils.py", line 348, in distributed_main
    main(cfg, **kwargs)
  File "../../evaluate.py", line 134, in main
    result, scores = eval_step(task, generator, models, sample, **kwargs)
  File "/home/user/ofa/utils/eval_utils.py", line 314, in eval_step
    return eval_glue(task, generator, models, sample, **kwargs)
  File "/home/user/ofa/utils/eval_utils.py", line 240, in eval_glue
    results = [{"hyp": hyp, "ref": ref_dict.keys()[0]} for hyp, ref_dict in zip(hyps, sample['ref_dict'])]
  File "/home/user/ofa/utils/eval_utils.py", line 240, in <listcomp>
    results = [{"hyp": hyp, "ref": ref_dict.keys()[0]} for hyp, ref_dict in zip(hyps, sample['ref_dict'])]
TypeError: 'dict_keys' object is not subscriptable
```

Could you provide some suggestions? I would appreciate your help.

**Comment by logicwong** [comment]
@taokz Sorry for the late reply. Try setting `{"hyp": hyp, "ref": ref_dict.keys()[0]}` to `{"hyp": hyp, "ref": ref_dict}` ? Also, the `eval_glue` function is not complete (we didn't test this function carefully). You can try to modify this function yourself to get the result.
