### ISSUE TITLE
vocab size of dict didn't match checkpoint 

### ISSUE THREAD

**Issue by yangjianxin1** [OFA-Sys/OFA#315]
I download the chinese checkpoint of Finetuned checkpoint for MUGE Caption (Stage 1),but the shape of encoder.embed_tokens.weight is [30325, 768], and the vocab size of utils/BERT_CN_dict/vocab.txt is 21128.They are not the same size.

**Comment by JustinLin610** [comment]
You met loading problems?  The difference comes from the addition of the image vq tokens(8192 tokens) and bounding box tokens (1000), and several functional tokens.

**Comment by yangjianxin1** [comment]
> You met loading problems? The difference comes from the addition of the image vq tokens(8192 tokens) and bounding box tokens (1000), and several functional tokens.

why do you add other tokens to the word_embedding in chinese. there is no problem with english bpe tokenizer

**Comment by yangjianxin1** [comment]
where is the code of chinese bert tokenizer in the project, I would like to read the code to learn, thx~

**Comment by JustinLin610** [comment]
> > You met loading problems? The difference comes from the addition of the image vq tokens(8192 tokens) and bounding box tokens (1000), and several functional tokens.
> 
> why do you add other tokens to the word_embedding in chinese. there is no problem with english bpe tokenizer

This is because of the pretraining setup, as it has tasks like  image infilling and visual grounding, and thus similar to the OFA English pretraining, the other tokens are added to the embedding. So what is the detailed problem of your experiments? Any more details like logs?

**Comment by JustinLin610** [comment]
> where is the code of chinese bert tokenizer in the project, I would like to read the code to learn, thx~

See `bpe_dir=../../utils/BERT_CN_dict` in `generate_caption_cn.sh`. For more details, you can dive into https://github.com/OFA-Sys/OFA/blob/main/data/mm_data/caption_dataset.py  In all, the change is a switch from gpt2 bpe to bert bpe with a Chinese vocabulary.
