### ISSUE TITLE
Difference between training scripts

### ISSUE THREAD

**Issue by 25icecreamflavors** [OFA-Sys/OFA#316]
What is the difference between training scripts for refcoco? I see the original one, bitfit, adapter and el.

**Comment by JustinLin610** [comment]
The scripts for prefix tuning, bitfit and adapters are related to one of our following studies: [Prompt Tuning for Generative Multimodal Pretrained Models](https://arxiv.org/abs/2208.02532). EL is contributed by Guangxiang Zhao, and see his paper [Well-classified Examples are Underestimated in Classification with Deep Neural Networks](https://arxiv.org/abs/2110.06537).
