### ISSUE TITLE
Hello, would like to know when you plan to open the pre-training code?

### ISSUE THREAD

**Issue by jexz11** [OFA-Sys/OFA#32]
Hello, would like to know when you plan to open the pre-training code? Recently wanted to generate new Pokemon models using text generated images from a dataset of Pokemon images. I found the model written by your team on the leaderboard and would like to try it again.

**Comment by logicwong** [comment]
We plan to release the pretraining code this month. If you want to generate Pokémon images from text, it is recommended to use the text-to-image code we have released.

**Comment by logicwong** [comment]
@jexz11 We have released the pre-training code of ofa, hope it will help you in your work.

**Comment by jexz11** [comment]
Thanks, but I've been working on another project. But thank you for your reply to me

**Comment by logicwong** [comment]
I see...
