### ISSUE TITLE
time-consuming inference on image generation

### ISSUE THREAD

**Issue by victorup** [OFA-Sys/OFA#325]
Hi, 

I run `run_scripts/image_gen/image_gen_example.py` to generate some images by inputting a query. However, it takes 140s per query. I use 3090 for inference. Do you know how to accelerate inference? 

Thanks!

**Comment by victorup** [comment]
I  try to modify the following setting:
- task.cfg.sampling_times = 1
- beam=10
- Remove the clip sort
The inference time still needs 47s per image.

**Comment by jxst539246** [comment]
It's a known issue, as our image generation method needs to generate 1024 tokens autoregressively (for 256*256 resolution). As you have already found, reducing beam_size can accelerate the inference, but according to our previous experiments, the larger the number of samples, the higher the quality of top1 selected by the clip. I think this requires you to make a trade-off according to your needs.
