### ISSUE TITLE
How can I output one caption using image sequence?

### ISSUE THREAD

**Issue by funykatebird** [OFA-Sys/OFA#329]
I want to generate a video caption, but how can I use the image sequence?
I could not find out which part to modify to use more than one image for the caption.

**Comment by JustinLin610** [comment]
We did not release methods about processing videos. One way to perform this task might be computing visual features with our ResNet adaptor for the images and using average pooling to make them one feature matrix as the input to the transformer. Also, you can try using more complex ways for the pooling. 

BTW, we have done experiments on video with our new project OFASys. See if it can help. https://github.com/OFA-Sys/OFASys
