### ISSUE TITLE
Evaluation: TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by xcvil** [OFA-Sys/OFA#332]
In `evaluate.py` line 159:

```python
if isinstance(scores[0], tuple):
```

I would suggest considering the `NoneType` scenario, e.g., in `OFA/utils/eval_utils.py` line 55.

So it will be bug-free if you modify `evaluate.py` line 159 as below:

```python
if scores and isinstance(scores[0], tuple):
```

**Comment by JustinLin610** [comment]
Good! Review has started yet.
