### ISSUE TITLE
Fine-tuned checkpoints for visual grounding

### ISSUE THREAD

**Issue by 594zyc** [OFA-Sys/OFA#338]
Thanks for the amazing effect in organizing such a great open-sourced project. 

Just curious is the tiny/huge version of the fine-tuned mode for refcoco available anywhere, which can reproduce the result in Table 4 of the paper?

**Comment by JustinLin610** [comment]
Tiny and Huge finetuned models are not yet released, but they are on the release schedule.

**Comment by 594zyc** [comment]
Got it. Thank you!

**Comment by nermienkh** [comment]
Greetings,

Is there any update regarding the tiny finetuned model?
