### ISSUE TITLE
Cannot unzip caption_data.zip file

### ISSUE THREAD

**Issue by Duanmu0312** [OFA-Sys/OFA#339]
The provided **caption_data.zip** file is too large and the unzip failed.
Could you please help to provide a better way to process data files? Thanks!

**Comment by JustinLin610** [comment]
Is there any downloading problem?

**Comment by Duanmu0312** [comment]
I think it may not be a network problem. I tried to download it twice and downloaded it completely, but it was unziped and reported an error. Can you provide a link to Google or Baidu network disk?发自我的 iPhone在 2023年1月11日，19:25，Junyang Lin ***@***.***> 写道：﻿
Is there any downloading problem?

**Comment by Duanmu0312** [comment]
Thank you for your advice, I used another computer and another network, successfully obtained a non-destructive compressed file, thank you.
