### ISSUE TITLE
When open the data preprocessing scripts?

### ISSUE THREAD

**Issue by guangzhaocs** [OFA-Sys/OFA#36]
I want to run OFA on my only data. So when will you open the data preprocessing scripts? Thanks very much.

**Comment by JustinLin610** [comment]
Which task are you referring to?

**Comment by guangzhaocs** [comment]
Visual Entailment. 

Maybe I can write by myself following the dataset format ^_^ It would be better if you could provide.

**Comment by JustinLin610** [comment]
The data should be organized as follows (separated by tabs): `uniq_id image_id image(base64 string) hypothesis caption(or text premise) label`

To transform images to base64 strings, you can use the following code:
```
from PIL import Image
from io import BytesIO
import base64

img = Image.open(fn)
img_buffer = BytesIO()
img.save(img_buffer, format=img.format)
byte_data = img_buffer.getvalue()
base64_str = base64.b64encode(byte_data) # bytes
```

**Comment by guangzhaocs** [comment]
Thanks.

**Comment by lostnighter** [comment]
Hi, I want to generate image_code on some custom datasets.  When will you open the data preprocessing scripts for image_code in image_gen dataset? Thanks very much.

**Comment by jxst539246** [comment]
we have upload the data preprocess script for  image generation task. Please check run_scripts/image_gen/generate_for_vqgan_code.sh.
