### ISSUE TITLE
Does Visual Grounding Task support fine-tuning?

### ISSUE THREAD

**Issue by Practicing7** [OFA-Sys/OFA#368]
I have noticed that in your ModelScope documents, you said that OFA now only supports the training of "mnli、caption、ocr", these three tasks.

**Comment by JustinLin610** [comment]
https://github.com/OFA-Sys/OFA/tree/main/run_scripts/refcoco check this directory and see if it helps

**Comment by Practicing7** [comment]
Thank you! I will check this.
