### ISSUE TITLE
add_tokens for tokenizer

### ISSUE THREAD

**Issue by SilyRab** [OFA-Sys/OFA#382]
Why add these tokens for tokenizer? 
`tokenizer.add_tokens(["<code_{}>".format(i) for i in range(8192)])`
`okenizer.add_tokens(["<bin_{}>".format(i) for i in range(1000)])`

**Comment by huizyuan** [comment]
I think the code token means the token of image patch. Meanwhile, I wonder how does the number of tokens (i.e., 8192) come from? How to embedding an image patch (16*16 pixel) to a single code?

**Comment by SilyRab** [comment]
It is more alikely about code generation. I have found some clues in the codes.

**Comment by logicwong** [comment]
@huizyuan We use [VQGAN](https://github.com/CompVis/taming-transformers) to transform the raw images into codes. 8192 is the number of codebook entries.

![image](https://github.com/OFA-Sys/OFA/assets/36780733/f4238ae6-aebc-4df2-a9fd-a3494250b382)
