### ISSUE TITLE
How to obtain Accuracy for Visual Grounding after running evaluation code

### ISSUE THREAD

**Issue by makanju0la** [OFA-Sys/OFA#385]
So this should be a quick one. If anybody has pointers or suggestions please let me know.

I have finished fine-tuning OFA for Visual Grounding and I ran the evaluation scripts. After running the evaluation scripts, JSON files for the eval data were generated and stored in a result folder like the one below:

<img width="307" alt="Screenshot 2023-04-07 at 12 22 30 PM" src="https://user-images.githubusercontent.com/48253625/230643153-63a656bd-97c7-436d-a77a-ae3a91ceaf59.png">

And when I open one of them, I notice that they are a collection of image IDs and bounding boxes. 

{
        "uniq_id": "751_0",
        "box": [
            113.42108154296875,
            44.214996337890625,
            335.1368713378906,
            265.28997802734375
        ]
    },
    {
        "uniq_id": "751_1",
        "box": [
            113.42108154296875,
            44.214996337890625,
            335.1368713378906,
            265.28997802734375
        ]
    }

Now I need to obtain the accuracy as shown on the OFA GitHub homepage. I thought there should be a script to obtain the accuracies but I cannot find it. If anyone knows where I can find the scripts please let me know. On the other hand, how have people computed accuracy? Should I just come up with a script by myself?

**Comment by logicwong** [comment]
@makanju0la The accuracy will be printed after running the evaluation scripts, you can check the output on the console.
