### ISSUE TITLE
custom image inference

### ISSUE THREAD

**Issue by SangMyeongWoh** [OFA-Sys/OFA#39]
I just want to test my custom image with code

can you let me know what model used for image extraction?

I mean, I want to know label and checkpoint info of Vin VL

**Comment by yangapku** [comment]
Hi, may I ask which task are you working on? To transform raw images to base64 strings, you can use the following code:
```
from PIL import Image
from io import BytesIO
import base64

img = Image.open(image_path)
img_buffer = BytesIO()
img.save(img_buffer, format=img.format)
byte_data = img_buffer.getvalue()
base64_str = base64.b64encode(byte_data) # bytes
```
In general, the object labels produced by VinVL are not necessary for OFA inference, which do not affect much to model performance.
