### ISSUE TITLE
VQGAN 模型的版本

### ISSUE THREAD

**Issue by PhoebusSi** [OFA-Sys/OFA#390]
请问下OFA是用的那个版本的VQAGAN模型？可否上传下checpont和config.yaml文件或者提供下链接？

**Comment by logicwong** [comment]
@PhoebusSi 直接对256x256编码那确实是1024长度。预训练时做的是image infilling，即还原图像中间部分的code，图像中部（128x128分辨率）编码出来的长度才是256
