### ISSUE TITLE
Why only three parameters were output

### ISSUE THREAD

**Issue by zhongfansun** [OFA-Sys/OFA#393]
I try to run stage1 of the image captioning task, but encounter an issue. I follow the instructions
I download _ofa_large.pt_ in _/home/szf/OFA/checkpoints/_
![image](https://github.com/OFA-Sys/OFA/assets/102452634/6c38bd4d-6a98-4e84-90a3-0a34de596acf)
Then I unzip the datesets _caption_data.zip_ in _/home/szf/OFA/dataset/caption_data/_
![image](https://github.com/OFA-Sys/OFA/assets/102452634/f2ed21d3-16fa-4799-a6fc-07f8c8e29fb0)
When I run the code and only three parameters are output. 
![image](https://github.com/OFA-Sys/OFA/assets/102452634/5c318442-f274-48a5-a6b3-a7b4a86c325f)
Looking forward to your response, thank you.

**Comment by logicwong** [comment]
@zhongfansun try modifying the script to

```
for max_epoch in 2 do
  echo "max_epoch "${max_epoch}
  for warmup_ratio in 0.06 do
    echo "warmup_ratio "${warmup_ratio}
    for drop_worst_after in 2500 do
      echo "drop_worst_after "${drop_worst_after}
```

If you use nohup, the log will be saved in train_stage1.out

**Comment by yuezih** [comment]
Hi @zhongfansun, I encountered the same issue. Have you solved it?
