### ISSUE TITLE
Finetuned BASE checkpoints

### ISSUE THREAD

**Issue by lostnighter** [OFA-Sys/OFA#40]
Could you please release the finetuned BASE checkpoints of different downstream tasks? It seems you release finetuned LARGE checkpoints.
Thanks

**Comment by logicwong** [comment]
We will release the finetuned BASE checkpoint on VQA this week, and then gradually release finetuned checkpoint on other tasks. Stay tuned.

**Comment by logicwong** [comment]
@lostnighter Hi, we have released the finetuned BASE checkpoints for Image Captioning, VQA, SNLI-VE and RefCOCO. Please check the latest code and have a try :)

**Comment by lostnighter** [comment]
@logicwong Hi, could you please provide the finetuned BASE checkpoints for Text-to-Image Generation task?

**Comment by jxst539246** [comment]
@lostnighter Hi, we have released the finetuned BASE checkpoint for Text-to-Image Generation task.

**Comment by lostnighter** [comment]
@jxst539246 Thanks! I'll try it.
