### ISSUE TITLE
file 'ocr_scene_test.tsv' missing

### ISSUE THREAD

**Issue by TequilaSR** [OFA-Sys/OFA#415]
Hi, thanks for your amazing work! I found that for OFA-OCR the file 'ocr_scene_test.tsv' used in run_scripts/ocr/evaluate_ocr.sh is not in the repo. Would you please help to provide this tsv file and the script for generating it?

**Comment by JasonLeeFdu** [comment]
+1

**Comment by JasonLeeFdu** [comment]
> Hi, thanks for your amazing work! I found that for OFA-OCR the file 'ocr_scene_test.tsv' used in run_scripts/ocr/evaluate_ocr.sh is not in the repo. Would you please help to provide this tsv file and the script for generating it?

have you found it, man?
