### ISSUE TITLE
I wonder how to make my own captioning datasets

### ISSUE THREAD

**Issue by cxy990729** [OFA-Sys/OFA#42]
Hi, I want to know how to get uniq-id and extract predicted object labels ?
could you provide me with the script to extract predicted object labels ?
could you provide me with the script to generate tsv files about my own captioning  @datasets ? @logicwong

**Comment by SangMyeongWoh** [comment]
> 1. uniq_id is a number (or string) that identifies the sample, you can specify it yourself (like 1-N).
> 2. In fact, we don't use predicted object labels in image captioning. You don't need to consider this field, just set it to an empty string.
> 3. You only need to organize your caption data as follows (separated by tabs): `uniq_id, image_id, caption, predicted object labels (set to empty string), image (base64 string)`
> 
> Where the image_id is also a number (or string) that identifies the image. To transform images to base64 strings, you can use the following code:
> 
> ```
> from PIL import Image
> from io import BytesIO
> import base64
> 
> img = Image.open(fn)
> img_buffer = BytesIO()
> img.save(img_buffer, format=img.format)
> byte_data = img_buffer.getvalue()
> base64_str = base64.b64encode(byte_data) # bytes
> ```

Is it fine if I let 'caption' as empty?

I just want to inference with my custom dataset

**Comment by logicwong** [comment]
> Is it fine if I let 'caption' as empty?
> 
> I just want to inference with my custom dataset

That's ok.
