### ISSUE TITLE
Where should I modify if I want to modify the architecture based on OFA model ?

### ISSUE THREAD

**Issue by dannyxiaocn** [OFA-Sys/OFA#43]
Hi, I am trying some minor changes to ofa base model and doing the same experiments as OFA. I have modify the models/ofa/unified_transformer_layer.py for bottom layer design, and register as ('ofa', 'tuning ofa') in the models/ofa/ofa.py. Is there anything I need to pay attention to? 
Also, if I need to load the weights from ofa_base checkpoints directly to the modified ofa ( tuning ofa ), where should I implement the special loading part? I am a little bit confused when finding in the code.
I will really appreciate it if you can help me!

**Comment by logicwong** [comment]
If you modify models/ofa/unified_transformer_layer.py, then when you use `--arch=ofa_base` or `--arch=ofa_large`, the training and inference of the model will be affected (after all, you have modified the model structure). It is recommended that you should ensure that the code you use is compatible with `ofa_base`, `ofa_large`, and your own `tuning ofa`.

Also, if you need to load the weights from ofa_base checkpoints to the modified ofa, the following things should be noted:
1. If you just add some new layers on the basis of ofa, then you can directly load the ofa_base checkpoints without any changes.
2. If you modify some layers of the original ofa, things are a little more troublesome. But I think you can try to modify the corresponding upgrade_state_dict_named function as follows (the red box part):
<img width="968" alt="65ECCF38-1A3E-41BB-8128-078729CC92B4" src="https://user-images.githubusercontent.com/36780733/158415680-9107bde1-9db7-459d-bf1a-2274553b91fc.png">

**Comment by dannyxiaocn** [comment]
Awesome! Thanks a lot. I will try it out.
