### ISSUE TITLE
original_id of items in datasets

### ISSUE THREAD

**Issue by lostnighter** [OFA-Sys/OFA#44]
Thanks for giving preprocessed datasets for finetuning. Each dataset only contains uniq_id without the original_id in its original dataset. For example, I get the caption_id of each item in neither image_gen datasets nor caption datasets. Could you please add the original_id to each item in the datasets or offer the connection file between the original_id and uniq_id.

**Comment by jxst539246** [comment]
We will update the preprocessed COCO datasets maybe next week.

**Comment by jxst539246** [comment]
Hi, we have uploaded the coco dataset with original_id for image_gen. please check the datasets.md.

**Comment by lostnighter** [comment]
@jxst539246 Thanks !
