### ISSUE TITLE
PIL.UnidentifiedImageError: cannot identify image file

### ISSUE THREAD

**Issue by SangMyeongWoh** [OFA-Sys/OFA#53]
I made tsv builder for custom image inference

but error occurs when I run it with my tsv file

**PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f8897ba1e50>**

I find that str convert into float64 automatically when I save tsv file with pandas

here's my custom make_tsv function

---------------------------------------------------------------------------------------

```
def make_tsv(datapath, img_list, start_index):

    data = pd.DataFrame({"unique_id": [], "img_id": [], "caption": [], "predicted_object_labels": [], "base64_str": []})
    for i, img_name in enumerate(img_list):
        print("index: ", i)
        print("img_name: ", img_name)
        img = Image.open(os.path.join(datapath, img_name))
        img_buffer = BytesIO()
        img.save(img_buffer, format=img.format)
        byte_data = img_buffer.getvalue()
        unique_id = start_index + i
        img_id = img_name.split(".")[-2]
        caption = ""
        predicted_object_labels = ""
        base64_str = base64.b64encode(byte_data)
        temp_dataframe = pd.DataFrame({"unique_id": [unique_id], "img_id": [img_id], "caption": [caption], \
                                            "predicted_object_labels": [predicted_object_labels], \
                                            "base64_str": [str(base64_str)]})

        data = pd.concat([data, temp_dataframe], ignore_index=True)
        
    return data
```

---------------------------------------------------------------------------------------

and I can't find solution yet.

can u give me advise??

**Comment by yangapku** [comment]
Hi, could you please share me the access to the image which you encounter PIL error with? Indeed, sometimes the PIL.Image.open will raise errors for some specific images (not so frequently). Meanwhile, it is recommended to replace the line `base64_str = base64.b64encode(byte_data)` with `base64_str = base64.b64encode(byte_data).decode("utf-8")`, which turns the `base64_str` from bytes to string.

**Comment by SangMyeongWoh** [comment]
> 

I already done it with that, but not works

In code below, origin is 'caption_test.tsv' and origin2 is my custom tsv

```
origin = pd.read_csv("dataset/caption_data/caption_test.tsv", sep='\t', header=None)
origin2 = pd.read_csv("coco2017_crop_mix/coco2017_crop_mix/test_crop_6/tsv_files/1_0.tsv", sep='\t', header=None)

print(type(origin.loc[0, 4]))
print(type(origin2.loc[0, 4]))

```

and result is here

![image](https://user-images.githubusercontent.com/43026418/159442280-63e0e21f-440e-48c4-9649-a55da532e536.png)

Is there any possibility of my images have problem?

**Comment by yangapku** [comment]
Hi, the definitions of the 4th-indexed columns are different between your tsv file (predicted_object_labels) and caption_test.tsv (base64_str). Please check the schema of your dataframe and make it conform with our provided tsv file.

**Comment by yangapku** [comment]
By the way, the necessity of using `base64_str = base64.b64encode(byte_data).decode("utf-8")` instead of `base64_str = base64.b64encode(byte_data)` is to avoid obtaining a string like "b'/9j/4AAQSkZJRgA'" in your tsv file and further cause some errors.

**Comment by SangMyeongWoh** [comment]
> Hi, the definitions of the 4th-indexed columns are different between your tsv file (predicted_object_labels) and caption_test.tsv (base64_str). Please check the schema of your dataframe and make it conform with our provided tsv file.

Im really appreciate with your aid.

I'll check what u said first.
