### ISSUE TITLE
custom training code

### ISSUE THREAD

**Issue by SangMyeongWoh** [OFA-Sys/OFA#54]
I just want to make custom training code with torch lightning

but I can't find model declaration and model config

where can I find it?

**Comment by logicwong** [comment]
See the files under `models/ofa`.

**Comment by SangMyeongWoh** [comment]
> See the files under `models/ofa`.

Im in try but I cant find model initializing part

Where OFAModel class initialized?

Could you give some advise?

I want use model like 

"model = OFAModel(args, encoder, decoder)"

where can I get initialized code?
