### ISSUE TITLE
model release

### ISSUE THREAD

**Issue by qyx51** [OFA-Sys/OFA#55]
Thanks for releasing the amazing work! 
Is there any plans to release the finetuned checkpoint for VQAv2 trained with Encouraging Loss?

**Comment by yangapku** [comment]
Hi, currently we do not set releasing this finetuned checkpoint to a very high priority. As we have mentioned in the past issue #34 , our latest best-performing VQAv2 checkpoint is finetuned under 640 * 640 image resolution for better performance, which costs much more than 1k inference GPU hours to obtain the reported result. We think very few users can afford the computation cost. It is more recommend to try Encouraging Loss on your own setting with lower image resolution (maybe the default 480 * 480). Please do not hesitate to contact us if you have any further questions!
