### ISSUE TITLE
model initialize part

### ISSUE THREAD

**Issue by SangMyeongWoh** [OFA-Sys/OFA#60]
Where OFAModel class initialized?

I want use model like

"model = OFAModel(args, encoder, decoder)"

but i cant find args, encoder, decoder init code each

where can I get initialized code?

**Comment by logicwong** [comment]
The model initialization part is in `models/ofa/unify_transformer.py` :
<img width="700" alt="F9CAB3C8-C3D9-430B-BE10-138D1FCA14E0" src="https://user-images.githubusercontent.com/36780733/160322464-b61c2cf0-ee82-4b92-90f5-c64647b3d85b.png">

The outer function of this part is in `tasks/ofa_task.py` :
<img width="657" alt="93FA6A5D-FEF8-48F8-99F9-B089D0EB65AE" src="https://user-images.githubusercontent.com/36780733/160322679-255278a4-a411-4b1d-8f28-90e6036a5525.png">

**Comment by SangMyeongWoh** [comment]
> The model initialization part is in `models/ofa/unify_transformer.py` : <img alt="F9CAB3C8-C3D9-430B-BE10-138D1FCA14E0" width="700" src="https://user-images.githubusercontent.com/36780733/160322464-b61c2cf0-ee82-4b92-90f5-c64647b3d85b.png">
> 
> The outer function of this part is in `tasks/ofa_task.py` : <img alt="93FA6A5D-FEF8-48F8-99F9-B089D0EB65AE" width="657" src="https://user-images.githubusercontent.com/36780733/160322679-255278a4-a411-4b1d-8f28-90e6036a5525.png">

thanks for your kindness

^O^

**Comment by SangMyeongWoh** [comment]
> 

![image](https://user-images.githubusercontent.com/43026418/160340225-59e195f4-e64b-4287-ae1f-963c7b6c865f.png)

I have one more question. I build simple CFG for model, and I got such essentials parsers for model.

its too many to check one by one.

where can i get a saved CFG?

I just want load model and forward it with my custom dataset.

**Comment by SangMyeongWoh** [comment]
> The model initialization part is in `models/ofa/unify_transformer.py` : <img alt="F9CAB3C8-C3D9-430B-BE10-138D1FCA14E0" width="700" src="https://user-images.githubusercontent.com/36780733/160322464-b61c2cf0-ee82-4b92-90f5-c64647b3d85b.png">
> 
> The outer function of this part is in `tasks/ofa_task.py` : <img alt="93FA6A5D-FEF8-48F8-99F9-B089D0EB65AE" width="657" src="https://user-images.githubusercontent.com/36780733/160322679-255278a4-a411-4b1d-8f28-90e6036a5525.png">

I have few more questions about bpe and tgt_dict

I find that 'tgt_dict' is initalized with Dictionary class in dictionary.py

Is that right??

and where can I get self.bpe initialize part?? I still cant find it


I always thanks for yours!

**Comment by logicwong** [comment]
@SangMyeongWoh Yes, 'tgt_dict' is initialized with Dictionary class in dictionary.py. self.bpe is initialized with GPT2BPE class in fairseq/fairseq/data/encoders/gpt2_bpe.py.

**Comment by SangMyeongWoh** [comment]
> @SangMyeongWoh Yes, 'tgt_dict' is initialized with Dictionary class in dictionary.py. self.bpe is initialized with GPT2BPE class in fairseq/fairseq/data/encoders/gpt2_bpe.py.

thanks a lot.

then, I think 'tgt_dict' and 'srt_dict' is initialized with same class

why they are seperated?? 

Is it ok if I use it with one initialized class??

**Comment by logicwong** [comment]
1. Yes, 'tgt_dict' and 'srt_dict' are initialized with the same class. We use 'src_dict' and 'tgt_dict' to build the embedding layers of encoder and decoder respectively, which are consistent with the original implementation of fairseq. It's ok to use only one dictionary, but I suggest that you'd better follow our code to avoid other problems.
2. The encoded result seems wrong. The standard practice is to use self.bpe to convert the raw text to subword sequence, and then convert the subword sequence into a tensor, as shown below:

```
def encode_text(self, text, length=None, append_bos=False, append_eos=False, use_bpe=True):
    s = self.tgt_dict.encode_line(
        line=self.bpe.encode(text) if use_bpe else text,
        add_if_not_exist=False,
        append_eos=False
    ).long()
    if length is not None:
        s = s[:length]
    if append_bos:
        s = torch.cat([self.bos_item, s])
    if append_eos:
        s = torch.cat([s, self.eos_item])
    return s

text = ' what does the image describe?'
res = encode_text(text, append_bos=True, append_eos=True, use_bpe=True)
```

**Comment by SangMyeongWoh** [comment]
> 1. Yes, 'tgt_dict' and 'srt_dict' are initialized with the same class. We use 'src_dict' and 'tgt_dict' to build the embedding layers of encoder and decoder respectively, which are consistent with the original implementation of fairseq. It's ok to use only one dictionary, but I suggest that you'd better follow our code to avoid other problems.
> 2. The encoded result seems wrong. The standard practice is to use self.bpe to convert the raw text to subword sequence, and then convert the subword sequence into a tensor, as shown below:
> 
> ```
> def encode_text(self, text, length=None, append_bos=False, append_eos=False, use_bpe=True):
>     s = self.tgt_dict.encode_line(
>         line=self.bpe.encode(text) if use_bpe else text,
>         add_if_not_exist=False,
>         append_eos=False
>     ).long()
>     if length is not None:
>         s = s[:length]
>     if append_bos:
>         s = torch.cat([self.bos_item, s])
>     if append_eos:
>         s = torch.cat([s, self.eos_item])
>     return s
> 
> text = ' what does the image describe?'
> res = encode_text(text, append_bos=True, append_eos=True, use_bpe=True)
> ```

I also use same encode_txt method and I recognize that result of **self.bpe.encode(" what does the image describe?")** is not weird.

but after encoded value walk through **self.tgt_dict.encode_line**, result become strange.

I think it happened because of Dictionary.

in my custom Dataset, I initialize Dictionary in __init__ such this way below

![image](https://user-images.githubusercontent.com/43026418/160754007-e7cc5dfb-ce31-4758-a534-eece166da792.png)

Should I do any other correct way?

**Comment by logicwong** [comment]
Which task are you working on?

**Comment by SangMyeongWoh** [comment]
> Which task are you working on?

captioning task. and I also have problem with load model

how can I build with your **caption_large_best_clean.pt**?

I just add classifier and test it with your model but its too hard to customize..

what should I prepare for OFAModel.build_model?

''
class Lightning_Model_OFA(pl.LightningModule):
    def __init__(self):
        self.state_dict = torch.load("checkpoints/caption_large_best_clean.pt")
        self.model = OFAModel.build_model(convert_namespace_to_omegaconf(self.state_dict['cfg']), \
                                          tasks.setup_task(self.state_dict['cfg']))
        self.model.load_state_dict(self.state_dict['model'])

    def forward(self, x):
        return self.model(x)
''

**Comment by SangMyeongWoh** [comment]
> Which task are you working on? And why don't you modify the existing code directly? For example, modify caption_dataset.py. Anyway, we have wrapped the code for initializing self.bpe and tgt_dict in ofa_task.py. When you create a new task, you only need to inherit the OFATask class, and then pass self.bpe and tgt_dict to the custom_dataset. In addition, custom_dataset should also inherit the OFADataset class.

thanks but I still dont know how to initialize task class.

can you give me some code example?

**Comment by logicwong** [comment]
> thanks but I still dont know how to initialize task class.
> 
> can you give me some code example?

see caption_task.py
