### ISSUE TITLE
Pretraining data release

### ISSUE THREAD

**Issue by lilisierrayu** [OFA-Sys/OFA#61]
Thanks for releasing the amazing work!
Will the pretraining data be released? There is very small number of examples available right now.

**Comment by logicwong** [comment]
RefCOCO/RefCOCO+/RefCOCOg: https://github.com/lichengunc/refer

**Comment by logicwong** [comment]
The pretraining datasets used in OFA are all publicly available. Here we provide the public links to these data, it is recommended that you download the data from the links first, and then process the downloaded dataset into a similar format as the examples we provided.

### **Links**

-   _CC12M_:  https://github.com/google-research-datasets/conceptual-12m
-   _CC3M_: https://github.com/google-research-datasets/conceptual-captions
-   _SBU_: https://www.cs.virginia.edu/~vicente/sbucaptions
-   _COCO_: https://cocodataset.org/#home
-   _VG_: https://visualgenome.org/
-   _VQAv2_: https://visualqa.org/
- _GQA_: https://cs.stanford.edu/people/dorarad/gqa/about.html
- _RefCOCO_/_RefCOCO+_/RefCOCOg: https://github.com/lichengunc/refer
-   _OpenImages_: https://storage.googleapis.com/openimages/web/index.html
-   _Object365_: https://www.objects365.org/overview.html
-   _YFCC100M (subset)_: https://github.com/openai/CLIP/blob/main/data/yfcc100m.md
-   _ImageNet-21K_: https://image-net.org/index.php
-   _Pile_: https://pile.eleuther.ai

**Comment by lilisierrayu** [comment]
Thank you very much for the response, and all those links are very helpful. 

In the paper appendix table8, Visual Genome data is used for captioning, visual grounding and object detection. I have questions about how it is processed for different tasks. 
1. Are all annotations of captioning and grounding data coming from the "region descriptions" file?
2. Which version of annotations (1.0, 1.2, 1.4) are used for object detection and for visual grounding/captioning ? 
3. For VG-Cap (may also for grounding), did you deduplicate similar regions? either by bounding box overlap, or by similarity of text description?

**Comment by logicwong** [comment]
> Thank you very much for the response, and all those links are very helpful.
> 
> In the paper appendix table8, Visual Genome data is used for captioning, visual grounding and object detection. I have questions about how it is processed for different tasks.
> 
> 1. Are all annotations of captioning and grounding data coming from the "region descriptions" file?
> 2. Which version of annotations (1.0, 1.2, 1.4) are used for object detection and for visual grounding/captioning ?
> 3. For VG-Cap (may also for grounding), did you deduplicate similar regions? either by bounding box overlap, or by similarity of text description?

1. Yes
2. 1.2
3. We don't deduplicate similar regions
