### ISSUE TITLE
What is the meaning of `train_caption_stage1_el.sh`?

### ISSUE THREAD

**Issue by shizhediao** [OFA-Sys/OFA#62]
I found that there are some files under the `caption` directory but do not know when should I use them.
What is the meaning and function of `train_caption_stage1_el.sh` and `train_caption_stage1_el_db.sh`
Thanks!

**Comment by JustinLin610** [comment]
This comes from the contribution of Guangxiang Zhao @zhaoguangxiang . EL refers to the encouraging loss (https://arxiv.org/pdf/2110.06537.pdf), and we add it to OFA as a feature as it can further enhance our model performance on the downstream tasks. See our latest News and the relevant readme files (https://github.com/OFA-Sys/OFA/blob/main/README_EncouragingLoss.md) for more information about EL.

**Comment by shizhediao** [comment]
ok thanks!
