### ISSUE TITLE
When i run the run_scripts/caption/train_caption_stage1.sh, i I encountered the following problem.

### ISSUE THREAD

**Issue by cxy990729** [OFA-Sys/OFA#64]
@logicwong 
Thanks for releasing the amazing  work!
When i run the run_scripts/caption/train_caption_stage1.sh, i I encountered the following problem. Can you help me?

train.py: error: argument --max-epoch: invalid int value: '{2,}'

train.py: error: argument --max-epoch: invalid int value: '{2,}'
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/pytorch-zme/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/miniconda3/envs/pytorch-zme/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/miniconda3/envs/pytorch-zme/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/ubuntu/miniconda3/envs/pytorch-zme/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/ubuntu/miniconda3/envs/pytorch-zme/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ubuntu/miniconda3/envs/pytorch-zme/bin/python3', '-u', '../../

**Comment by logicwong** [comment]
@cxy990729 Are you sure your local `train_caption_stage1.sh` is the same as the one on GitHub? Also, are you following the training procedures we provide?

<img width="913" alt="2A730A57-0FAB-4560-8BAF-39C01A546370" src="https://user-images.githubusercontent.com/36780733/161416106-dacfd98d-132e-4952-8cf1-252f195d0af4.png">

**Comment by cxy990729** [comment]
I am sure my train_caption_stage1.sh is the same as the one on GitHub.
train.py: error: argument --max-epoch: invalid int value: '{2,}'
subprocess.CalledProcessError: Command '['/home/ubuntu/miniconda3/envs/pytorch-zme/bin/python3',...]' returned non-zero exit status 2.

**Comment by cxy990729** [comment]
I think my shell version judge the ‘for grammar’(for max_epoch in {2,_}) is wrong.

**Comment by cxy990729** [comment]
I think my shell version judge the ‘for grammar’(for max_epoch in {2,_}) is wrong. @logicwong

**Comment by logicwong** [comment]
@logicwong OK, I see. The ‘for grammar’ is mainly used for hyper-parameter tuning. If you don't need to tune hyper-parameters, you can remove `for max_epoch in {2,_}` and set max_epoch directly.
