### ISSUE TITLE
Custom image captioning model in Chinese

### ISSUE THREAD

**Issue by zhuluntsai** [OFA-Sys/OFA#66]
Hello, I am doing the image captioning task in Chinese. Is there any way to switch the tokenization and word embedding method to my own method in the training process to adapt the OFA captioning model into Chinese?

**Comment by JustinLin610** [comment]
You can use the current vocabulary to process Chinese actually, but you may have longer sequences due to the encoding. An alternative is to create your own vocabulary (see ```utils/BPE``` for more details), and build a similar dictionary for Chinese.

**Comment by zhuluntsai** [comment]
Thanks for the advice! I will try this.
