### ISSUE TITLE
Query - Is this model capable of being served using tensorflow serving?

### ISSUE THREAD

**Issue by joeyouss** [OFA-Sys/OFA#71]
I would like to make use of an API that calls this model and upon research, the best prospect was to use tensorflow serving.
Can any maintainer confirm that this model can be served using tensorflow serving?
Thanks!

**Comment by joeyouss** [comment]
@JustinLin610

**Comment by JustinLin610** [comment]
We haven't done this yet, and so it is still unavailable.

**Comment by joeyouss** [comment]
Ok thanks for the reply!
