### ISSUE TITLE
How can I output multiple captions using beam search?

### ISSUE THREAD

**Issue by ZihaoZheng98** [OFA-Sys/OFA#74]
Hi, thanks for the wonderful work, I want to output 5 captions when I set "beam" to 5, but it seems to output only one caption by default, since this repository is rich in functionality, I could not find out which part to modify to output more than one caption for each image, can you help me?

**Comment by logicwong** [comment]
You can modify the `eval_caption` function in `OFA/utils/eval_utils.py`, for example:

```
def eval_caption(task, generator, models, sample, **kwargs):
    transtab = str.maketrans({key: None for key in string.punctuation})
    hypos = task.inference_step(generator, models, sample)
    results = []
    for i, sample_id in enumerate(sample["id"].tolist()):
        for j in range(len(hypos[i])):
            detok_hypo_str = decode_fn(hypos[i][j]["tokens"], task.tgt_dict, task.bpe, generator)
            results.append({"image_id": str(sample_id) + '_' + str(j), "caption": detok_hypo_str.translate(transtab).strip()})
    return results, None
```

**Comment by FingerRec** [comment]
![image](https://user-images.githubusercontent.com/20349006/225509185-f23328e2-c642-4e78-8d02-5c13364d68c6.png)

But the generated captions with this method are all the same :(
