### ISSUE TITLE
Checkpoint name attributed may needs updated for OFA_large

### ISSUE THREAD

**Issue by allanj** [OFA-Sys/OFA#77]
I downloaded the pre-trained `OFA-large` checkpoint here: https://ofa-beijing.oss-cn-beijing.aliyuncs.com/checkpoints/ofa_large.pt

And try to load the model by
```python3
task = tasks.setup_task(cfg.task)
models, cfg = checkpoint_utils.load_model_ensemble(
    pre_trained_model_path,
    task=task
)
```

But it doesn't work and it shows didn't find the corresponding model name.

Then I check the checkpoint , found the name is `m6_unify_large`

Then I modify this line https://github.com/OFA-Sys/OFA/blob/main/models/ofa/ofa.py#L320 to replace `ofa_large` to `m6_unify_large` then everything works fine.

I guess maybe need to update a bit the checkpoint state and upload again

**Comment by logicwong** [comment]
Thank you so much for pointing this out! We have updated and uploaded the `OFA-large` checkpoint.
