### ISSUE TITLE
for vqa beam search inference, how to get the confidence score (normalized in (0,1)) for the predicted answer

### ISSUE THREAD

**Issue by HiSultryMan** [OFA-Sys/OFA#82]

**Comment by logicwong** [comment]
You can modify the `eval_vqa` function in `OFA/utils/eval_utils.py`, like this (make sure to exclude the positional scores of the prefix_tokens):

<img width="989" alt="FC8A27A4-083F-48FB-A3AF-BDE3E9AD334D" src="https://user-images.githubusercontent.com/36780733/165079999-5e8be9cc-f76e-42c0-a157-e160e6fe02a2.png">

**Comment by HiSultryMan** [comment]
thanks for your reply. what about the confidence score for allcand search?

**Comment by logicwong** [comment]
@HiSultryMan 
<img width="608" alt="6ABCCEE8-177E-44DA-A9E7-7648C2ACE163" src="https://user-images.githubusercontent.com/36780733/165429130-d166a5ba-7aff-4825-ba3e-83e8f6316f2b.png">
