### ISSUE TITLE
Discussion: Experiments with SwinTransformer?

### ISSUE THREAD

**Issue by allanj** [OFA-Sys/OFA#83]
Just a discussion

I wonder if the authors have tried replacing the ResNet with SwinTransformers in such SimVLM architecture.

Under the SimVLM architecture, using SwinTransformers obtains way worse performance than ResNet in my experiment. I wonder if the authors have similar observations or any thoughts on this.

My replacement: simply replace the image embedding part.

**Comment by allanj** [comment]
This is not using OFA codebase, but more like an early experimental result on my side.

**Comment by JustinLin610** [comment]
Now we are working on ViT architectures as you did but we still do not have a conclusion. One question: are your ResNet and Swin pretrained (say, on ImageNet-1k) or randomly initialized?

**Comment by allanj** [comment]
yes, pretrained.

**Comment by JustinLin610** [comment]
Interesting! Any results on downstream tasks to support the conclusion of worse performance? As I am not familiar with Swin, I don't know if it has any requirements on training setups... That might influence a lot

**Comment by allanj** [comment]
I don't have a firm conclusion yet. The results are on our specific downstream task. yeah, maybe the training setups affect that as well. But anyway, thanks for the quick response and I will try more experiments
