### ISSUE TITLE
Code & checkpoint for image classification

### ISSUE THREAD

**Issue by swaggy-TN** [OFA-Sys/OFA#9]
Could you please release the code and checkpoint for image classification task? THX💗💗💗

**Comment by yangapku** [comment]
Thank you for your interest on OFA! We plan to release the code & checkpoint for image classification task before the end of March. Stay tuned for our later update 😄

**Comment by yangapku** [comment]
@swaggy-TN Hi, the code & checkpoint for image classification on ImageNet-1K have been released in this repo today! Please check the latest code and have a try :)

**Comment by swaggy-TN** [comment]
Thx for your effort💗💗💗
