### ISSUE TITLE
pretraining with the dataset examples

### ISSUE THREAD

**Issue by wfx0330** [OFA-Sys/OFA#90]
Thanks for your great works. While using the pretraing codes, my dataset is also use the examples for pretraining which was released by your codes. However, I have the following questions:
![OFA-1](https://user-images.githubusercontent.com/104745738/166185805-13606b8e-9386-4b78-8e01-cf938e699e87.png)

**Comment by logicwong** [comment]
@wfx0330 Please make sure your data format is correct, we recommend organizing your own datasets according to the pretraining samples we provide. For more details about the pretraining data formats, please refer to the pretraining section in README.

**Comment by wfx0330** [comment]
hi, after conferring your answers, I have already addressed the issue with the adjustment in the selected_cols. However,  the new issue is as the following:


Original Traceback (most recent call last):
  File "/home/zk/anaconda3/envs/ofa/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zk/anaconda3/envs/ofa/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/zk/multi-model/OFA-main/data/pretrain_data/unify_dataset.py", line 657, in collater
    samples_v2 += self.process_pure_image(0) if self.pure_image_dataset else []
  File "/home/zk/multi-model/OFA-main/data/pretrain_data/unify_dataset.py", line 423, in process_pure_image
    image = Image.open(BytesIO(base64.urlsafe_b64decode(image))).convert("RGB")
  File "/home/zk/anaconda3/envs/ofa/lib/python3.7/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/home/zk/anaconda3/envs/ofa/lib/python3.7/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
**binascii.Error: Invalid base64-encoded string: number of data characters (17121) cannot be 1 more than a multiple of 4**

**Comment by logicwong** [comment]
@wfx0330 Make sure your original images are not corrupted and correctly encoded as base64 strings. Try using urlsafe_b64encode, like this:

```
img = Image.open(fn)
img_buffer = BytesIO()
img.save(img_buffer, format=img.format)
byte_data = img_buffer.getvalue()
base64_str = base64.urlsafe_b64encode(byte_data) # bytes 
```

**Comment by logicwong** [comment]
@wfx0330 Hi, please also add a line `base64_str = base64_str.decode("utf-8")` after `base64_str = base64.b64encode(byte_data)`.  See #94 for more details.

**Comment by logicwong** [comment]
@wfx0330 For VQA-v2, I would recommend to use our processed [VQAv2 Dataset](url)[ ](https://ofa-beijing.oss-cn-beijing.aliyuncs.com/datasets/vqa_data/vqa_data.zip) directly. The training part of this dataset contains both VQAv2 and VG-QA samples. More details about this dataset can be referred to #56, #76 and [README](https://github.com/OFA-Sys/OFA)
