### ISSUE TITLE
Typo and finetune with HuggingFace model

### ISSUE THREAD

**Issue by chenxwh** [OFA-Sys/OFA#92]
Hi,

Thanks for supporting HuggingFace model! I noticed a typo in here https://github.com/OFA-Sys/OFA/blob/main/transformers.md (`it clone`), also a typo on the model card here https://huggingface.co/OFA-Sys/OFA-large (the title below shows OFA-tiny).

My main question is, is it possible to finetune on downstream tasks with the HuggingFace models? For example for VQA (fairseq codebase), there is a specific format to arrange the input, wondering whether it is possible to finetune with HuggingFace models and whether any requirement for the input? I notice in the readme `gen = model.generate(inputs, patch_images=patch_img, num_beams=4)`, should I give all the textual input to `inputs`, and does `num_beams=4` mean it is always does beam search?

Thank you!

**Comment by JustinLin610** [comment]
Thanks for your pointing out the typos. Training on transformers trainer has not been tested yet for now, but I'll have a try and update the branch if everything is alright. As to VQA, later I'll provide a checkpoint of OFA finetuned on VQA. I think what you need to do is similar the requirements in https://huggingface.co/spaces/OFA-Sys/OFA-Visual_Question_Answering, you give the question (textual input) to ```inputs```, and the image to ```patch_images```. As to beam search, if you turn it to ```1```, then you are using greedy search.
