### ISSUE TITLE
tiny model inference & finetuning

### ISSUE THREAD

**Issue by shayanjoya** [OFA-Sys/OFA#93]
Hi, Thank you for your work. Currently only pretrained OFA-Large and OFA-Base models are provided. Are you able to provide fine tuned model checkpoints for the tiny model? I'm interested in model inference using downstream tasks mainly image captioning.

**Comment by JustinLin610** [comment]
We have released the tiny pretrained model (see "Model Card" in our README). Currently we have no plan about releasing finetuned tiny models, and you can finetune on the pretrained model with our scripts for different tasks o get the checkpoints.
