### ISSUE TITLE
What's a grounded explanation for update_freq?

### ISSUE THREAD

**Issue by dannyxiaocn** [OFA-Sys/OFA#95]
Hello awesome researchers! When I change the update_freq while remaining batch_size the same, it seems no difference in the GPU memory taken. But as you have said, the actual batch_size is equal to update_freq * batch_size * num_of_gpu, so what's a grounded explanation ( Jiediqi ) of how update_freq is working?

**Comment by JustinLin610** [comment]
This is for gradient accumulation. Forward for ```update_freq``` times and accumulate the gradients, and then backward once.

**Comment by dannyxiaocn** [comment]
Great! Thank you so much.
