### ISSUE TITLE
How can I make batch_size in validation the same as hyperparameter --batch_size_valid?

### ISSUE THREAD

**Issue by dannyxiaocn** [OFA-Sys/OFA#96]
Hi, I am currently working on moe-ofa. When I am doing the experiments in Image Caption, I have encountered the following problem.
``` 
File "/workspace/OFA/fairseq/fairseq/modules/moe/moe_layer.py", line 120, in forward
logger.warning(f"padding batch with unexpected size {input_shape[0]} (expected: {expected_bsz})")
AssertionError: 10 < 2
```
It is just an assertion that the input valid batch_size is unexpected ( actual input is 10, but expected is 2 ). However, it works well in the training steps ( same input and expected ). So this really bothers me.
Btw, my code base is using fairseq-moe. You can also directly check my fork. 
I will really appreciate it if you can help me.

**Comment by yangapku** [comment]
Hi, since beam-search is used in the validation phase, the actual batch-size will be multiplied with 5, resulting in the tensor shape to be 2 * 5 = 10.

**Comment by dannyxiaocn** [comment]
Thanks a lot! The validation is running, but it is always stuck there with the GPU-Util 100%, while still normal in training. Do you have any clue about this?
Again, I will really appreciate it if you can help me.
<img width="566" alt="image" src="https://user-images.githubusercontent.com/43365671/167235257-03530dc8-c1c8-4411-8f6a-d661b514bd33.png">

**Comment by yangapku** [comment]
Hi, a 100% GPU-Util tends to happen when some workers are waiting for other workers for communication. Please check the code snippets related to communication operations. I will also take a further look into this issue.

**Comment by yangapku** [comment]
Hi, a 100% GPU-Util tends to happen when some workers are waiting for other workers for communication. Please check the code snippets related to communication operations. I will also take a further look into this issue.

**Comment by yangapku** [comment]
Hi @dannyxiaocn , I think the issue is indeed related to the hang of communication operations. In fact, during validation, the model will make generation on the validation samples, which has a not-fixed number of decoding steps across the workers with batches from different data shards. However, the workers will still make All2All communications across all the workers for MoE in each decoding step, which will cause a hang for workers with more decoding steps than others.
