### ISSUE TITLE
Training on a single GPU

### ISSUE THREAD

**Issue by debalabbas** [OFA-Sys/OFA#97]
Can we finetune the model on a single GPU, if yes can someone please guide me on how to do that.

**Comment by logicwong** [comment]
Yes, you can change `CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --nproc_per_node=4 --master_port=${MASTER_PORT} ../../train.py \` to `CUDA_VISIBLE_DEVICES=0 python3 ../../train.py \`

**Comment by debalabbas** [comment]
Thanks
